// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** Platform accounts the team connected to Inboxapp. Every thread belongs to one, and messages are sent from one. */
export class AccountLinks {
  /**
   * List account links
   *
   * `GET /account-links`
   *
   * @throws {AccountLinksListError}
   */
  readonly list: PaginatedMethod<T.AccountLinksListRequest, T.AccountLinkPage, T.AccountLink>;
  /**
   * Get account link
   *
   * `GET /account-links/{accountLinkId}`
   *
   * @throws {AccountLinksGetError}
   */
  readonly get: Method<T.AccountLinksGetRequest, T.AccountLink>;

  constructor(transport: Transport) {
    this.list = transport.paginated(Operations.accountLinksList);
    this.get = transport.method(Operations.accountLinksGet);
  }
}
