// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** The colors of Inboxapp's palette, for tags and statuses. */
export class Colors {
  /**
   * List colors
   *
   * `GET /colors`
   *
   * @throws {ColorsListError}
   */
  readonly list: Method<T.ColorsListRequest, Array<T.Color>>;

  constructor(transport: Transport) {
    this.list = transport.method(Operations.colorsList);
  }
}
