// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** The team's record of a person, holding its CRM state: status, tags, notes, valuation and default assignee. A contact groups one or more profiles, a person's accounts on the platforms. */
export class Contacts {
  /**
   * Find contacts
   *
   * Finds contacts by the platform identity of one of their profiles: a `platform` with `platformId` or `username`.
   *
   * `GET /contacts`
   *
   * @throws {ContactsListError}
   */
  readonly list: PaginatedMethod<T.ContactsListRequest, T.ContactPage, T.Contact>;
  /**
   * Get contact
   *
   * `GET /contacts/{contactId}`
   *
   * @throws {ContactsGetError}
   */
  readonly get: Method<T.ContactsGetRequest, T.Contact>;
  /**
   * Update contact
   *
   * `PATCH /contacts/{contactId}`
   *
   * @throws {ContactsUpdateError}
   */
  readonly update: Method<T.ContactsUpdateRequest, T.Contact>;
  /**
   * Add tag to contact
   *
   * Adding a tag the contact already has succeeds.
   *
   * `PUT /contacts/{contactId}/tags/{tagRef}`
   *
   * @throws {ContactsAddTagError}
   */
  readonly addTag: Method<T.ContactsAddTagRequest, void>;
  /**
   * Remove tag from contact
   *
   * Removing a tag the contact doesn't have succeeds.
   *
   * `DELETE /contacts/{contactId}/tags/{tagRef}`
   *
   * @throws {ContactsRemoveTagError}
   */
  readonly removeTag: Method<T.ContactsRemoveTagRequest, void>;

  constructor(transport: Transport) {
    this.list = transport.paginated(Operations.contactsList);
    this.get = transport.method(Operations.contactsGet);
    this.update = transport.method(Operations.contactsUpdate);
    this.addTag = transport.method(Operations.contactsAddTag);
    this.removeTag = transport.method(Operations.contactsRemoveTag);
  }
}
