// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import { ApiError } from "../errors.ts";
import type * as T from "./types.ts";

/** `400 invalidRequest` */
export class InvalidRequest extends ApiError<"invalidRequest", T.InvalidRequestDetails> {
  override name = "InvalidRequest";
}

/** `401 unauthorized` */
export class Unauthorized extends ApiError<"unauthorized", null> {
  override name = "Unauthorized";
}

/** `429 rateLimited` */
export class RateLimited extends ApiError<"rateLimited", T.RateLimitedDetails> {
  override name = "RateLimited";
}

/** `500 internal` */
export class Internal extends ApiError<"internal", null> {
  override name = "Internal";
}

/** `400 invalidCursor` */
export class InvalidCursor extends ApiError<"invalidCursor", null> {
  override name = "InvalidCursor";
}

/** `404 memberNotFound` */
export class MemberNotFound extends ApiError<"memberNotFound", null> {
  override name = "MemberNotFound";
}

/** `403 platformNotAvailable` */
export class PlatformNotAvailable extends ApiError<
  "platformNotAvailable",
  T.PlatformNotAvailableDetails
> {
  override name = "PlatformNotAvailable";
}

/** `404 accountLinkNotFound` */
export class AccountLinkNotFound extends ApiError<"accountLinkNotFound", null> {
  override name = "AccountLinkNotFound";
}

/** `404 contactNotFound` */
export class ContactNotFound extends ApiError<"contactNotFound", null> {
  override name = "ContactNotFound";
}

/** `403 workspaceLocked` */
export class WorkspaceLocked extends ApiError<"workspaceLocked", null> {
  override name = "WorkspaceLocked";
}

/** `404 tagNotFound` */
export class TagNotFound extends ApiError<"tagNotFound", null> {
  override name = "TagNotFound";
}

/** `404 threadNotFound` */
export class ThreadNotFound extends ApiError<"threadNotFound", null> {
  override name = "ThreadNotFound";
}

/** `409 accountLinkDisconnected` */
export class AccountLinkDisconnected extends ApiError<
  "accountLinkDisconnected",
  T.AccountLinkDisconnectedDetails
> {
  override name = "AccountLinkDisconnected";
}

/** `409 integrationSetupRequired` */
export class IntegrationSetupRequired extends ApiError<
  "integrationSetupRequired",
  T.IntegrationSetupRequiredDetails
> {
  override name = "IntegrationSetupRequired";
}

/** `422 capabilityNotSupported` */
export class CapabilityNotSupported extends ApiError<
  "capabilityNotSupported",
  T.CapabilityNotSupportedDetails
> {
  override name = "CapabilityNotSupported";
}

/** `429 platformRateLimited` */
export class PlatformRateLimited extends ApiError<
  "platformRateLimited",
  T.PlatformRateLimitedDetails
> {
  override name = "PlatformRateLimited";
}

/** `502 platformError` */
export class PlatformError extends ApiError<"platformError", null> {
  override name = "PlatformError";
}

/** `503 platformUnavailable` */
export class PlatformUnavailable extends ApiError<
  "platformUnavailable",
  T.PlatformUnavailableDetails
> {
  override name = "PlatformUnavailable";
}

/** `404 messageNotFound` */
export class MessageNotFound extends ApiError<"messageNotFound", null> {
  override name = "MessageNotFound";
}

/** `422 threadRestricted` */
export class ThreadRestricted extends ApiError<"threadRestricted", T.ThreadRestrictedDetails> {
  override name = "ThreadRestricted";
}

/** `422 mutationWindowClosed` */
export class MutationWindowClosed extends ApiError<
  "mutationWindowClosed",
  T.MutationWindowClosedDetails
> {
  override name = "MutationWindowClosed";
}

/** `422 messageNotModifiable` */
export class MessageNotModifiable extends ApiError<
  "messageNotModifiable",
  T.MessageNotModifiableDetails
> {
  override name = "MessageNotModifiable";
}

/** `422 contentRejected` */
export class ContentRejected extends ApiError<"contentRejected", T.ContentRejectedDetails> {
  override name = "ContentRejected";
}

/** `403 planRequired` */
export class PlanRequired extends ApiError<"planRequired", T.PlanRequiredDetails> {
  override name = "PlanRequired";
}

/** `409 sendInProgress` */
export class SendInProgress extends ApiError<"sendInProgress", T.SendInProgressDetails> {
  override name = "SendInProgress";
}

/** `422 idempotencyKeyReused` */
export class IdempotencyKeyReused extends ApiError<"idempotencyKeyReused", null> {
  override name = "IdempotencyKeyReused";
}

/** `422 recipientUnavailable` */
export class RecipientUnavailable extends ApiError<
  "recipientUnavailable",
  T.RecipientUnavailableDetails
> {
  override name = "RecipientUnavailable";
}

/** `422 platformNotSupported` */
export class PlatformNotSupported extends ApiError<
  "platformNotSupported",
  T.PlatformNotSupportedDetails
> {
  override name = "PlatformNotSupported";
}

/** `422 profileAmbiguous` */
export class ProfileAmbiguous extends ApiError<"profileAmbiguous", T.ProfileAmbiguousDetails> {
  override name = "ProfileAmbiguous";
}

/** `502 sendUnconfirmed` */
export class SendUnconfirmed extends ApiError<"sendUnconfirmed", T.SendUnconfirmedDetails> {
  override name = "SendUnconfirmed";
}

/** `409 nameTaken` */
export class NameTaken extends ApiError<"nameTaken", T.NameTakenDetails> {
  override name = "NameTaken";
}

/** `422 tagLimitReached` */
export class TagLimitReached extends ApiError<"tagLimitReached", T.TagLimitReachedDetails> {
  override name = "TagLimitReached";
}

/** `404 statusNotFound` */
export class StatusNotFound extends ApiError<"statusNotFound", null> {
  override name = "StatusNotFound";
}

/** The error class of every `code` this SDK version knows. */
export const errorsByCode = {
  invalidRequest: InvalidRequest,
  unauthorized: Unauthorized,
  rateLimited: RateLimited,
  internal: Internal,
  invalidCursor: InvalidCursor,
  memberNotFound: MemberNotFound,
  platformNotAvailable: PlatformNotAvailable,
  accountLinkNotFound: AccountLinkNotFound,
  contactNotFound: ContactNotFound,
  workspaceLocked: WorkspaceLocked,
  tagNotFound: TagNotFound,
  threadNotFound: ThreadNotFound,
  accountLinkDisconnected: AccountLinkDisconnected,
  integrationSetupRequired: IntegrationSetupRequired,
  capabilityNotSupported: CapabilityNotSupported,
  platformRateLimited: PlatformRateLimited,
  platformError: PlatformError,
  platformUnavailable: PlatformUnavailable,
  messageNotFound: MessageNotFound,
  threadRestricted: ThreadRestricted,
  mutationWindowClosed: MutationWindowClosed,
  messageNotModifiable: MessageNotModifiable,
  contentRejected: ContentRejected,
  planRequired: PlanRequired,
  sendInProgress: SendInProgress,
  idempotencyKeyReused: IdempotencyKeyReused,
  recipientUnavailable: RecipientUnavailable,
  platformNotSupported: PlatformNotSupported,
  profileAmbiguous: ProfileAmbiguous,
  sendUnconfirmed: SendUnconfirmed,
  nameTaken: NameTaken,
  tagLimitReached: TagLimitReached,
  statusNotFound: StatusNotFound,
} as const;

export type ErrorsByCode = typeof errorsByCode;

export type KnownApiError = InstanceType<ErrorsByCode[keyof ErrorsByCode]>;

/** `throttling` failures were never processed; `transient` ones may have been. */
export const retryableCodes = {
  rateLimited: "throttling",
  internal: "transient",
  platformRateLimited: "throttling",
  platformError: "transient",
  platformUnavailable: "transient",
  sendInProgress: "transient",
} as const;

/** Errors any operation can fail with. */
export type CommonError = InvalidRequest | Unauthorized | RateLimited | Internal;

export type PlatformsListError = CommonError;

export type TeamGetError = CommonError;

export type TeamListMembersError = InvalidCursor | CommonError;

export type TeamGetMemberError = MemberNotFound | CommonError;

export type AccountLinksListError = InvalidCursor | PlatformNotAvailable | CommonError;

export type AccountLinksGetError = PlatformNotAvailable | AccountLinkNotFound | CommonError;

export type ContactsListError = InvalidCursor | PlatformNotAvailable | CommonError;

export type ContactsGetError = PlatformNotAvailable | ContactNotFound | CommonError;

export type ContactsUpdateError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ContactNotFound
  | CommonError;

export type ContactsAddTagError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ContactNotFound
  | TagNotFound
  | CommonError;

export type ContactsRemoveTagError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ContactNotFound
  | TagNotFound
  | CommonError;

export type ThreadsListError = InvalidCursor | PlatformNotAvailable | CommonError;

export type ThreadsGetError = PlatformNotAvailable | ThreadNotFound | CommonError;

export type ThreadsUpdateError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ThreadNotFound
  | CommonError;

export type ThreadsDeleteError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ThreadNotFound
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | CapabilityNotSupported
  | PlatformRateLimited
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type ThreadsTypingError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | ThreadNotFound
  | CapabilityNotSupported
  | CommonError;

export type MessagesListError = InvalidCursor | PlatformNotAvailable | ThreadNotFound | CommonError;

export type MessagesGetError = PlatformNotAvailable | MessageNotFound | CommonError;

export type MessagesEditError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | MessageNotFound
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | ThreadRestricted
  | MutationWindowClosed
  | MessageNotModifiable
  | ContentRejected
  | CapabilityNotSupported
  | PlatformRateLimited
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type MessagesUnsendError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | MessageNotFound
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | ThreadRestricted
  | MutationWindowClosed
  | MessageNotModifiable
  | ContentRejected
  | CapabilityNotSupported
  | PlatformRateLimited
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type MessagesSendError =
  | PlatformNotAvailable
  | PlanRequired
  | WorkspaceLocked
  | ThreadNotFound
  | ContactNotFound
  | AccountLinkNotFound
  | SendInProgress
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | IdempotencyKeyReused
  | ThreadRestricted
  | ContentRejected
  | RecipientUnavailable
  | PlatformNotSupported
  | ProfileAmbiguous
  | CapabilityNotSupported
  | PlatformRateLimited
  | SendUnconfirmed
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type MessagesHistoryError = PlatformNotAvailable | MessageNotFound | CommonError;

export type MessagesReactError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | MessageNotFound
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | ThreadRestricted
  | MutationWindowClosed
  | MessageNotModifiable
  | ContentRejected
  | CapabilityNotSupported
  | PlatformRateLimited
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type MessagesUnreactError =
  | PlatformNotAvailable
  | WorkspaceLocked
  | MessageNotFound
  | AccountLinkDisconnected
  | IntegrationSetupRequired
  | ThreadRestricted
  | MutationWindowClosed
  | MessageNotModifiable
  | ContentRejected
  | CapabilityNotSupported
  | PlatformRateLimited
  | PlatformError
  | PlatformUnavailable
  | CommonError;

export type MessagesAttachmentError = PlatformNotAvailable | MessageNotFound | CommonError;

export type TagsListError = CommonError;

export type TagsCreateError = WorkspaceLocked | NameTaken | TagLimitReached | CommonError;

export type TagsGetError = TagNotFound | CommonError;

export type TagsUpdateError = WorkspaceLocked | TagNotFound | NameTaken | CommonError;

export type TagsDeleteError = WorkspaceLocked | TagNotFound | CommonError;

export type StatusesListError = CommonError;

export type StatusesCreateError = WorkspaceLocked | NameTaken | CommonError;

export type StatusesGetError = StatusNotFound | CommonError;

export type StatusesUpdateError = WorkspaceLocked | StatusNotFound | NameTaken | CommonError;

export type StatusesDeleteError = WorkspaceLocked | StatusNotFound | CommonError;

export type ColorsListError = CommonError;

export type EventsListError = CommonError;
