// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** Changes in the team, as delivered to v2 webhooks. Each event names the object that changed and carries only the values of the change; read the object for its current state. Events are kept for 7 days, up to 25,000 per team. */
export class Events {
  /**
   * Replay events
   *
   * Reads events in sequence order. A page can hold fewer than `limit` events when some are filtered out; continue from `lastSeq` while `hasMore` is true.
   *
   * `GET /events`
   *
   * @throws {EventsListError}
   */
  readonly list: PaginatedMethod<T.EventsListRequest, T.EventPage, T.EventPageDataItem>;

  constructor(transport: Transport) {
    this.list = transport.paginated(Operations.eventsList);
  }
}
