// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Transport } from "../transport.ts";
import { AccountLinks } from "./account-links.ts";
import { Colors } from "./colors.ts";
import { Contacts } from "./contacts.ts";
import { Events } from "./events.ts";
import { Messages } from "./messages.ts";
import { Platforms } from "./platforms.ts";
import { Statuses } from "./statuses.ts";
import { Tags } from "./tags.ts";
import { Team } from "./team.ts";
import { Threads } from "./threads.ts";

export class Services {
  /** The messaging platforms available to the team, with what each one supports. */
  readonly platforms: Platforms;
  /** The team the API token belongs to, and its members: the Inboxapp users who work in it. */
  readonly team: Team;
  /** Platform accounts the team connected to Inboxapp. Every thread belongs to one, and messages are sent from one. */
  readonly accountLinks: AccountLinks;
  /** The team's record of a person, holding its CRM state: status, tags, notes, valuation and default assignee. A contact groups one or more profiles, a person's accounts on the platforms. */
  readonly contacts: Contacts;
  /** Conversations between one of the team's account links and one profile. */
  readonly threads: Threads;
  /** Messages in a thread, and sending, editing, unsending and reacting to them on the platform. */
  readonly messages: Messages;
  /** Labels the team puts on contacts. */
  readonly tags: Tags;
  /** The pipeline stages a contact can be in, such as a deal stage. A contact has at most one. */
  readonly statuses: Statuses;
  /** The colors of Inboxapp's palette, for tags and statuses. */
  readonly colors: Colors;
  /** Changes in the team, as delivered to v2 webhooks. Each event names the object that changed and carries only the values of the change; read the object for its current state. Events are kept for 7 days, up to 25,000 per team. */
  readonly events: Events;

  constructor(transport: Transport) {
    this.platforms = new Platforms(transport);
    this.team = new Team(transport);
    this.accountLinks = new AccountLinks(transport);
    this.contacts = new Contacts(transport);
    this.threads = new Threads(transport);
    this.messages = new Messages(transport);
    this.tags = new Tags(transport);
    this.statuses = new Statuses(transport);
    this.colors = new Colors(transport);
    this.events = new Events(transport);
  }
}
