// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** Messages in a thread, and sending, editing, unsending and reacting to them on the platform. */
export class Messages {
  /**
   * List messages
   *
   * `GET /threads/{threadId}/messages`
   *
   * @throws {MessagesListError}
   */
  readonly list: PaginatedMethod<T.MessagesListRequest, T.MessagePage, T.Message>;
  /**
   * Get message
   *
   * `GET /messages/{messageId}`
   *
   * @throws {MessagesGetError}
   */
  readonly get: Method<T.MessagesGetRequest, T.Message>;
  /**
   * Edit message
   *
   * Edits the message on the platform. Needs `message:edit`, within the platform's edit window.
   *
   * `PATCH /messages/{messageId}`
   *
   * @throws {MessagesEditError}
   */
  readonly edit: Method<T.MessagesEditRequest, T.Message>;
  /**
   * Delete message
   *
   * `DELETE /messages/{messageId}`
   *
   * @throws {MessagesUnsendError}
   */
  readonly unsend: Method<T.MessagesUnsendRequest, T.MessageDeletion>;
  /**
   * Send message
   *
   * `201` for a new send. A replay of an `Idempotency-Key` returns the original result with `200`.
   *
   * `POST /messages`
   *
   * @throws {MessagesSendError}
   */
  readonly send: Method<T.MessagesSendRequest, T.MessagesSendResponse>;
  /**
   * Get message history
   *
   * Every version of the message's content, from its edits.
   *
   * `GET /messages/{messageId}/history`
   *
   * @throws {MessagesHistoryError}
   */
  readonly history: Method<T.MessagesHistoryRequest, T.MessageHistory>;
  /**
   * Add reaction
   *
   * `POST /messages/{messageId}/reactions`
   *
   * @throws {MessagesReactError}
   */
  readonly react: Method<T.MessagesReactRequest, T.Reactions>;
  /**
   * Remove reaction
   *
   * `DELETE /messages/{messageId}/reactions`
   *
   * @throws {MessagesUnreactError}
   */
  readonly unreact: Method<T.MessagesUnreactRequest, T.Reactions>;
  /**
   * Get attachment
   *
   * `200` with a fresh URL once ready, `202` while the media is pending or processing. A card index is `invalidRequest`.
   *
   * `GET /messages/{messageId}/attachments/{index}`
   *
   * @throws {MessagesAttachmentError}
   */
  readonly attachment: Method<T.MessagesAttachmentRequest, T.AttachmentMedia>;

  constructor(transport: Transport) {
    this.list = transport.paginated(Operations.messagesList);
    this.get = transport.method(Operations.messagesGet);
    this.edit = transport.method(Operations.messagesEdit);
    this.unsend = transport.method(Operations.messagesUnsend);
    this.send = transport.method(Operations.messagesSend);
    this.history = transport.method(Operations.messagesHistory);
    this.react = transport.method(Operations.messagesReact);
    this.unreact = transport.method(Operations.messagesUnreact);
    this.attachment = transport.method(Operations.messagesAttachment);
  }
}
