// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { OperationDescriptor } from "../wire.ts";

export const platformsList = {
  id: "platforms.list",
  method: "GET",
  path: "/platforms",
} as const satisfies OperationDescriptor;

export const teamGet = {
  id: "team.get",
  method: "GET",
  path: "/team",
} as const satisfies OperationDescriptor;

export const teamListMembers = {
  id: "team.listMembers",
  method: "GET",
  path: "/members",
  query: { limit: { name: "limit", style: "form" }, cursor: { name: "cursor", style: "form" } },
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;

export const teamGetMember = {
  id: "team.getMember",
  method: "GET",
  path: "/members/{memberId}",
  labels: ["memberId"],
} as const satisfies OperationDescriptor;

export const accountLinksList = {
  id: "accountLinks.list",
  method: "GET",
  path: "/account-links",
  query: {
    platform: { name: "platform", style: "form" },
    status: { name: "status", style: "form" },
    limit: { name: "limit", style: "form" },
    cursor: { name: "cursor", style: "form" },
  },
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;

export const accountLinksGet = {
  id: "accountLinks.get",
  method: "GET",
  path: "/account-links/{accountLinkId}",
  labels: ["accountLinkId"],
} as const satisfies OperationDescriptor;

export const contactsList = {
  id: "contacts.list",
  method: "GET",
  path: "/contacts",
  query: {
    platform: { name: "platform", style: "form" },
    platformId: { name: "platformId", style: "form" },
    username: { name: "username", style: "form" },
    expand: { name: "expand", style: "form" },
    limit: { name: "limit", style: "form" },
    cursor: { name: "cursor", style: "form" },
  },
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;

export const contactsGet = {
  id: "contacts.get",
  method: "GET",
  path: "/contacts/{contactId}",
  labels: ["contactId"],
  query: { expand: { name: "expand", style: "form" } },
} as const satisfies OperationDescriptor;

export const contactsUpdate = {
  id: "contacts.update",
  method: "PATCH",
  path: "/contacts/{contactId}",
  labels: ["contactId"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const contactsAddTag = {
  id: "contacts.addTag",
  method: "PUT",
  path: "/contacts/{contactId}/tags/{tagRef}",
  labels: ["contactId", "tagRef"],
} as const satisfies OperationDescriptor;

export const contactsRemoveTag = {
  id: "contacts.removeTag",
  method: "DELETE",
  path: "/contacts/{contactId}/tags/{tagRef}",
  labels: ["contactId", "tagRef"],
} as const satisfies OperationDescriptor;

export const threadsList = {
  id: "threads.list",
  method: "GET",
  path: "/threads",
  query: {
    accountLinkId: { name: "accountLinkId", style: "form" },
    platform: { name: "platform", style: "form" },
    contactId: { name: "contactId", style: "form" },
    folder: { name: "folder", style: "form" },
    tag: { name: "tag", style: "form" },
    status: { name: "status", style: "form" },
    assigneeId: { name: "assigneeId", style: "form" },
    unassigned: { name: "unassigned", style: "form" },
    campaignId: { name: "campaignId", style: "form" },
    q: { name: "q", style: "form" },
    order: { name: "order", style: "form" },
    expand: { name: "expand", style: "form" },
    limit: { name: "limit", style: "form" },
    cursor: { name: "cursor", style: "form" },
  },
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;

export const threadsGet = {
  id: "threads.get",
  method: "GET",
  path: "/threads/{threadId}",
  labels: ["threadId"],
  query: { expand: { name: "expand", style: "form" } },
} as const satisfies OperationDescriptor;

export const threadsUpdate = {
  id: "threads.update",
  method: "PATCH",
  path: "/threads/{threadId}",
  labels: ["threadId"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const threadsDelete = {
  id: "threads.delete",
  method: "DELETE",
  path: "/threads/{threadId}",
  labels: ["threadId"],
} as const satisfies OperationDescriptor;

export const threadsTyping = {
  id: "threads.typing",
  method: "POST",
  path: "/threads/{threadId}/typing",
  labels: ["threadId"],
} as const satisfies OperationDescriptor;

export const messagesList = {
  id: "messages.list",
  method: "GET",
  path: "/threads/{threadId}/messages",
  labels: ["threadId"],
  query: {
    order: { name: "order", style: "form" },
    expand: { name: "expand", style: "form" },
    limit: { name: "limit", style: "form" },
    cursor: { name: "cursor", style: "form" },
  },
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;

export const messagesGet = {
  id: "messages.get",
  method: "GET",
  path: "/messages/{messageId}",
  labels: ["messageId"],
  query: { expand: { name: "expand", style: "form" } },
} as const satisfies OperationDescriptor;

export const messagesEdit = {
  id: "messages.edit",
  method: "PATCH",
  path: "/messages/{messageId}",
  labels: ["messageId"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const messagesUnsend = {
  id: "messages.unsend",
  method: "DELETE",
  path: "/messages/{messageId}",
  labels: ["messageId"],
  query: { scope: { name: "scope", style: "form" } },
} as const satisfies OperationDescriptor;

export const messagesSend = {
  id: "messages.send",
  method: "POST",
  path: "/messages",
  headers: { idempotencyKey: "Idempotency-Key" },
  hasBody: true,
  responseCode: "httpStatus",
} as const satisfies OperationDescriptor;

export const messagesHistory = {
  id: "messages.history",
  method: "GET",
  path: "/messages/{messageId}/history",
  labels: ["messageId"],
} as const satisfies OperationDescriptor;

export const messagesReact = {
  id: "messages.react",
  method: "POST",
  path: "/messages/{messageId}/reactions",
  labels: ["messageId"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const messagesUnreact = {
  id: "messages.unreact",
  method: "DELETE",
  path: "/messages/{messageId}/reactions",
  labels: ["messageId"],
  query: { emoji: { name: "emoji", style: "form" } },
} as const satisfies OperationDescriptor;

export const messagesAttachment = {
  id: "messages.attachment",
  method: "GET",
  path: "/messages/{messageId}/attachments/{index}",
  labels: ["messageId", "index"],
} as const satisfies OperationDescriptor;

export const tagsList = {
  id: "tags.list",
  method: "GET",
  path: "/tags",
} as const satisfies OperationDescriptor;

export const tagsCreate = {
  id: "tags.create",
  method: "POST",
  path: "/tags",
  hasBody: true,
} as const satisfies OperationDescriptor;

export const tagsGet = {
  id: "tags.get",
  method: "GET",
  path: "/tags/{tagRef}",
  labels: ["tagRef"],
} as const satisfies OperationDescriptor;

export const tagsUpdate = {
  id: "tags.update",
  method: "PATCH",
  path: "/tags/{tagRef}",
  labels: ["tagRef"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const tagsDelete = {
  id: "tags.delete",
  method: "DELETE",
  path: "/tags/{tagRef}",
  labels: ["tagRef"],
} as const satisfies OperationDescriptor;

export const statusesList = {
  id: "statuses.list",
  method: "GET",
  path: "/statuses",
} as const satisfies OperationDescriptor;

export const statusesCreate = {
  id: "statuses.create",
  method: "POST",
  path: "/statuses",
  hasBody: true,
} as const satisfies OperationDescriptor;

export const statusesGet = {
  id: "statuses.get",
  method: "GET",
  path: "/statuses/{statusRef}",
  labels: ["statusRef"],
} as const satisfies OperationDescriptor;

export const statusesUpdate = {
  id: "statuses.update",
  method: "PATCH",
  path: "/statuses/{statusRef}",
  labels: ["statusRef"],
  hasBody: true,
} as const satisfies OperationDescriptor;

export const statusesDelete = {
  id: "statuses.delete",
  method: "DELETE",
  path: "/statuses/{statusRef}",
  labels: ["statusRef"],
} as const satisfies OperationDescriptor;

export const colorsList = {
  id: "colors.list",
  method: "GET",
  path: "/colors",
} as const satisfies OperationDescriptor;

export const eventsList = {
  id: "events.list",
  method: "GET",
  path: "/events",
  query: {
    afterSeq: { name: "afterSeq", style: "form" },
    type: { name: "type", style: "form" },
    limit: { name: "limit", style: "form" },
  },
  pagination: {
    mode: "sequence",
    inputToken: "afterSeq",
    outputToken: "lastSeq",
    items: "data",
    hasNextPage: "hasMore",
    pageSize: "limit",
  },
} as const satisfies OperationDescriptor;
