// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** The messaging platforms available to the team, with what each one supports. */
export class Platforms {
  /**
   * List platforms
   *
   * Each platform's capabilities and limits. An account link's `capabilities` can only narrow its platform's.
   *
   * `GET /platforms`
   *
   * @throws {PlatformsListError}
   */
  readonly list: Method<T.PlatformsListRequest, Array<T.PlatformInfo>>;

  constructor(transport: Transport) {
    this.list = transport.method(Operations.platformsList);
  }
}
