// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** The pipeline stages a contact can be in, such as a deal stage. A contact has at most one. */
export class Statuses {
  /**
   * List statuses
   *
   * `GET /statuses`
   *
   * @throws {StatusesListError}
   */
  readonly list: Method<T.StatusesListRequest, T.StatusPage>;
  /**
   * Create status
   *
   * `POST /statuses`
   *
   * @throws {StatusesCreateError}
   */
  readonly create: Method<T.StatusesCreateRequest, T.Status>;
  /**
   * Get status
   *
   * `GET /statuses/{statusRef}`
   *
   * @throws {StatusesGetError}
   */
  readonly get: Method<T.StatusesGetRequest, T.Status>;
  /**
   * Update status
   *
   * `PATCH /statuses/{statusRef}`
   *
   * @throws {StatusesUpdateError}
   */
  readonly update: Method<T.StatusesUpdateRequest, T.Status>;
  /**
   * Delete status
   *
   * `DELETE /statuses/{statusRef}`
   *
   * @throws {StatusesDeleteError}
   */
  readonly delete: Method<T.StatusesDeleteRequest, void>;

  constructor(transport: Transport) {
    this.list = transport.method(Operations.statusesList);
    this.create = transport.method(Operations.statusesCreate);
    this.get = transport.method(Operations.statusesGet);
    this.update = transport.method(Operations.statusesUpdate);
    this.delete = transport.method(Operations.statusesDelete);
  }
}
