// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** Labels the team puts on contacts. */
export class Tags {
  /**
   * List tags
   *
   * `GET /tags`
   *
   * @throws {TagsListError}
   */
  readonly list: Method<T.TagsListRequest, T.TagPage>;
  /**
   * Create tag
   *
   * `POST /tags`
   *
   * @throws {TagsCreateError}
   */
  readonly create: Method<T.TagsCreateRequest, T.Tag>;
  /**
   * Get tag
   *
   * `GET /tags/{tagRef}`
   *
   * @throws {TagsGetError}
   */
  readonly get: Method<T.TagsGetRequest, T.Tag>;
  /**
   * Update tag
   *
   * `PATCH /tags/{tagRef}`
   *
   * @throws {TagsUpdateError}
   */
  readonly update: Method<T.TagsUpdateRequest, T.Tag>;
  /**
   * Delete tag
   *
   * Also removes it from every contact.
   *
   * `DELETE /tags/{tagRef}`
   *
   * @throws {TagsDeleteError}
   */
  readonly delete: Method<T.TagsDeleteRequest, void>;

  constructor(transport: Transport) {
    this.list = transport.method(Operations.tagsList);
    this.create = transport.method(Operations.tagsCreate);
    this.get = transport.method(Operations.tagsGet);
    this.update = transport.method(Operations.tagsUpdate);
    this.delete = transport.method(Operations.tagsDelete);
  }
}
