// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** The team the API token belongs to, and its members: the Inboxapp users who work in it. */
export class Team {
  /**
   * Get team
   *
   * `GET /team`
   *
   * @throws {TeamGetError}
   */
  readonly get: Method<T.TeamGetRequest, T.Team>;
  /**
   * List members
   *
   * `GET /members`
   *
   * @throws {TeamListMembersError}
   */
  readonly listMembers: PaginatedMethod<T.TeamListMembersRequest, T.MemberPage, T.Member>;
  /**
   * Get member
   *
   * `GET /members/{memberId}`
   *
   * @throws {TeamGetMemberError}
   */
  readonly getMember: Method<T.TeamGetMemberRequest, T.Member>;

  constructor(transport: Transport) {
    this.get = transport.method(Operations.teamGet);
    this.listMembers = transport.paginated(Operations.teamListMembers);
    this.getMember = transport.method(Operations.teamGetMember);
  }
}
