// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type { Method, PaginatedMethod, Transport } from "../transport.ts";
import * as Operations from "./operations.ts";
import type * as T from "./types.ts";

/** Conversations between one of the team's account links and one profile. */
export class Threads {
  /**
   * List threads
   *
   * Threads in inbox order, filtered by folder and by contact CRM state.
   *
   * `GET /threads`
   *
   * @throws {ThreadsListError}
   */
  readonly list: PaginatedMethod<T.ThreadsListRequest, T.ThreadPage, T.Thread>;
  /**
   * Get thread
   *
   * `GET /threads/{threadId}`
   *
   * @throws {ThreadsGetError}
   */
  readonly get: Method<T.ThreadsGetRequest, T.Thread>;
  /**
   * Update thread
   *
   * `PATCH /threads/{threadId}`
   *
   * @throws {ThreadsUpdateError}
   */
  readonly update: Method<T.ThreadsUpdateRequest, T.Thread>;
  /**
   * Delete thread
   *
   * Deletes the conversation on the platform when it can, and always in Inboxapp. The response's `scope` says which happened.
   *
   * `DELETE /threads/{threadId}`
   *
   * @throws {ThreadsDeleteError}
   */
  readonly delete: Method<T.ThreadsDeleteRequest, T.ThreadDeletion>;
  /**
   * Send typing indicator
   *
   * Shows the account link as typing in the conversation. At most one per thread every 2.5 seconds; extra calls return `skipped`.
   *
   * `POST /threads/{threadId}/typing`
   *
   * @throws {ThreadsTypingError}
   */
  readonly typing: Method<T.ThreadsTypingRequest, T.TypingSignal>;

  constructor(transport: Transport) {
    this.list = transport.paginated(Operations.threadsList);
    this.get = transport.method(Operations.threadsGet);
    this.update = transport.method(Operations.threadsUpdate);
    this.delete = transport.method(Operations.threadsDelete);
    this.typing = transport.method(Operations.threadsTyping);
  }
}
