// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

export interface PlatformsListRequest {}

/** What a platform supports. Account links narrow its capabilities, and threads narrow them further through `restrictions`. */
export interface PlatformInfo {
  platform: Platform;
  name: string;
  /** Prepended to a `username` to display it. Empty when the platform uses none. */
  usernamePrefix: string;
  /** The platform's baseline. Each account link narrows it in its own `capabilities`. */
  capabilities: Array<PlatformInfoCapabilitiesItem>;
  /** Limits checked before a send reaches the platform. */
  limits: PlatformInfoLimits;
  /** Seconds after a message's `createdAt` during which a capability still applies to it, such as `message:edit`. A capability without an entry has no window. */
  mutationWindows: PlatformInfoMutationWindows;
  threadState: PlatformInfoThreadState;
}

/** The platform. Every team can use twitter; a team may have others enabled. */
export type Platform = string;

export type PlatformInfoCapabilitiesItem =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

/** Limits checked before a send reaches the platform. */
export interface PlatformInfoLimits {
  /** Maximum characters in a message, counting an emoji as one. Null when the platform sets none. */
  characters: number | null;
  /** Maximum attachments in a message. Null when the platform sets none. */
  mediaCount: number | null;
  /** Maximum size of one attachment. Null when the platform sets none. */
  mediaBytes: number | null;
  /** Accepted formats per media kind: MIME types, families such as `image/*`, or extensions such as `.pdf`. A kind without an entry accepts nothing. Null accepts any format. */
  mediaTypes: PlatformInfoLimitsMediaTypes | null;
}

export interface PlatformInfoLimitsMediaTypes {
  image?: Array<string>;
  video?: Array<string>;
  gif?: Array<string>;
  file?: Array<string>;
  audio?: Array<string>;
}

/** Seconds after a message's `createdAt` during which a capability still applies to it, such as `message:edit`. A capability without an entry has no window. */
export interface PlatformInfoMutationWindows {
  "message:send"?: number;
  "message:edit"?: number;
  "message:delete:self"?: number;
  "message:unsend"?: number;
  "message:react"?: number;
  "message:reply"?: number;
  "message:forward"?: number;
  "media:image"?: number;
  "media:video"?: number;
  "media:gif"?: number;
  "media:file"?: number;
  "media:audio"?: number;
  "thread:typing:send"?: number;
  "thread:typing:receive"?: number;
  "thread:message-requests"?: number;
  "thread:delete:remote"?: number;
  "directory:typeahead"?: number;
  "thread:archive:observe"?: number;
  "thread:archive:mutate"?: number;
  "thread:read:observe"?: number;
  "thread:read:mutate"?: number;
  "profile:follow"?: number;
  "profile:unfollow"?: number;
}

export interface PlatformInfoThreadState {
  /** Null when the platform has no such state. */
  archive: PlatformInfoThreadStateArchive | null;
  /** Null when the platform has no such state. */
  read: PlatformInfoThreadStateRead | null;
}

export interface PlatformInfoThreadStateArchive {
  /** Inboxapp reads this state from the platform. */
  observe: boolean;
  /** Changing it in Inboxapp also changes it on the platform. */
  mutate: boolean;
}

export interface PlatformInfoThreadStateRead {
  /** Inboxapp reads this state from the platform. */
  observe: boolean;
  /** Changing it in Inboxapp also changes it on the platform. */
  mutate: boolean;
}

export interface InvalidRequestDetails {
  issues: Array<InvalidRequestDetailsIssuesItem>;
}

export interface InvalidRequestDetailsIssuesItem {
  path: Array<InvalidRequestDetailsIssuesItemPathItem>;
  message: string;
}

export type InvalidRequestDetailsIssuesItemPathItem = string | number;

export interface RateLimitedDetails {
  window: RateLimitedDetailsWindow;
  limit: number;
  resetAt: string;
}

export type RateLimitedDetailsWindow = "minute" | "hour" | "day" | (string & {});

export interface TeamGetRequest {}

/** The team the API token belongs to. */
export interface Team {
  id: string;
  name: string;
  /** The team's URL segment in Inboxapp. */
  slug: string;
  imageUrl: string | null;
  /** The ISO 4217 code contact valuations are in. */
  currency: string;
  /** Whether the team lets Inboxapp support open its workspace. */
  allowSupportAccess: boolean;
  createdAt: string;
}

export interface TeamListMembersRequest {
  /** Page size, from 1 to 100. Defaults to 50. */
  limit?: number;
  /** The previous page's `nextCursor`. Opaque, and valid only with the filters it was issued for. */
  cursor?: string;
}

/** Ordered by `createdAt`, oldest first. */
export interface MemberPage {
  data: Array<Member>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

/** A person on the team, who can be assigned threads and contacts. */
export interface Member {
  /** The member ID that `assigneeId` fields take. */
  id: string;
  name: string | null;
  email: string;
  imageUrl: string | null;
  /** `owner` and `admin` manage the team. A `user` can't change settings, billing or members. */
  role: MemberRole;
  createdAt: string;
}

/** `owner` and `admin` manage the team. A `user` can't change settings, billing or members. */
export type MemberRole = "owner" | "admin" | "user" | (string & {});

export type Cuid2 = string;

export interface TeamGetMemberRequest {
  memberId: Cuid2;
}

/** `active` sends and syncs. `paused` is stopped for the reasons in `pauseReasons`, and resumes once none remain. `offline` lost its connection to the platform and must be reconnected in Inboxapp. */
export type AccountLinksListRequestStatusItem = "active" | "offline" | "paused";

export interface AccountLinksListRequest {
  /** Repeat the key to match any of several. */
  platform?: Array<Platform>;
  /** Repeat the key to match any of several. */
  status?: Array<AccountLinksListRequestStatusItem>;
  /** Page size, from 1 to 100. Defaults to 50. */
  limit?: number;
  /** The previous page's `nextCursor`. Opaque, and valid only with the filters it was issued for. */
  cursor?: string;
}

/** Ordered by `createdAt`, oldest first. */
export interface AccountLinkPage {
  data: Array<AccountLink>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

/** A platform account the team connected to Inboxapp. Every conversation and message goes through one. */
export interface AccountLink {
  id: string;
  platform: Platform;
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string;
  /** The platform username without its display prefix. Lookups take this form. */
  username: string | null;
  displayName: string | null;
  avatarUrl: string | null;
  /** `active` sends and syncs. `paused` is stopped for the reasons in `pauseReasons`, and resumes once none remain. `offline` lost its connection to the platform and must be reconnected in Inboxapp. */
  status: AccountLinkStatus;
  /** Why the account link is paused. New reasons may be added. */
  pauseReasons: Array<string>;
  /** What this account can do: its platform's capabilities, narrowed for this account. An operation it lacks fails with `capabilityNotSupported`. */
  capabilities: Array<AccountLinkCapabilitiesItem>;
  /** When Inboxapp finished importing the account's conversations. Null until then. */
  syncedAt: string | null;
  createdAt: string;
}

/** `active` sends and syncs. `paused` is stopped for the reasons in `pauseReasons`, and resumes once none remain. `offline` lost its connection to the platform and must be reconnected in Inboxapp. */
export type AccountLinkStatus = "active" | "offline" | "paused" | (string & {});

export type AccountLinkCapabilitiesItem =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

export interface PlatformNotAvailableDetails {
  platform: Platform;
}

export interface AccountLinksGetRequest {
  accountLinkId: Cuid2;
}

export type ContactsListRequestExpandItem = "status" | "tags" | "assignee";

export interface ContactsListRequest {
  platform: Platform;
  /** Contacts with a profile of this platform ID. Give this or the other identity filter, repeating the key for up to 100. No match is an empty page. */
  platformId?: Array<string>;
  /** Contacts with a profile of this username, without its display prefix. One username may match several contacts. Give this or the other identity filter, repeating the key for up to 100. No match is an empty page. */
  username?: Array<string>;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<ContactsListRequestExpandItem>;
  /** Page size, from 1 to 100. Defaults to 50. */
  limit?: number;
  /** The previous page's `nextCursor`. Opaque, and valid only with the filters it was issued for. */
  cursor?: string;
}

/** Ordered by `createdAt`, oldest first. */
export interface ContactPage {
  data: Array<Contact>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

/** The team's record of a person: their profiles, plus the team's CRM state about them. */
export interface Contact {
  id: string;
  /** The person's profiles, oldest link first. Profiles on platforms unavailable to the team are left out. */
  profiles: Array<Profile>;
  /** A status: a pipeline stage on the team's board. */
  statusId: string | null;
  tagIds: Array<string>;
  notes: string | null;
  /** What the person is worth to the team, in the team's `currency`. */
  valuation: number | null;
  /** The default assignee of this contact's threads that have none of their own. */
  assigneeId: string | null;
  createdAt: string;
  updatedAt: string;
  status?: Status;
  tags?: Array<Tag>;
  assignee?: Member;
}

/** One person's account on one platform. Profile data is shared across teams; the team's own data about the person is on their contact. */
export interface Profile {
  id: string;
  platform: Platform;
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string;
  /** The platform username without its display prefix. Lookups take this form. */
  username: string;
  /** The username as the platform displays it. Show this, and look up by `username`. */
  handle: string;
  displayName: string;
  avatarUrl: string | null;
  bio: string | null;
  location: string | null;
  websiteUrl: string | null;
  websiteDomain: string | null;
  /** The platform vouches for the account, such as with an X badge. Platform-specific badges are in `platformData`. */
  verified: boolean;
  /** A company or page rather than a person. */
  isOrganization: boolean;
  /** The account's posts are visible only to approved followers. */
  isProtected: boolean;
  followerCount: number | null;
  followingCount: number | null;
  postCount: number | null;
  /** On X, how many posts the user has liked. */
  engagementCount: number | null;
  /** On X, how many lists include the profile. */
  listedCount: number | null;
  /** `suspended` by the platform, or `notFound` when deleted or deactivated. */
  accountStatus: ProfileAccountStatus;
  /** When the account was created on the platform. */
  platformCreatedAt: string | null;
  profileUrl: string | null;
  /** When Inboxapp last stored a change to this profile. */
  updatedAt: string;
  platformData: ProfilePlatformData;
}

/** `suspended` by the platform, or `notFound` when deleted or deactivated. */
export type ProfileAccountStatus = "active" | "suspended" | "notFound" | (string & {});

/** Fields only one platform has, tagged by `_tag`. Ignore tags you don't know. */
export type ProfilePlatformData = ProfilePlatformDataTwitter | ProfilePlatformDataOther;

export interface ProfilePlatformDataTwitter {
  _tag: "twitter";
  badge: ProfilePlatformDataTwitterBadge | null;
  profileType: ProfilePlatformDataTwitterProfileType;
  professionalCategory: string | null;
  urlEntities: Array<ProfilePlatformDataTwitterUrlEntitiesItem>;
  bannerUrl: string | null;
  rawData: Record<string, unknown> | null;
}

export type ProfilePlatformDataTwitterBadge = "blue" | "gold" | "gray" | (string & {});

export type ProfilePlatformDataTwitterProfileType =
  | "personal"
  | "business"
  | "government"
  | (string & {});

export interface ProfilePlatformDataTwitterUrlEntitiesItem {
  url: string;
  expandedUrl: string;
  displayUrl: string;
  indices: [number, number];
}

/** A platform the team has enabled beyond those every team can use. Its fields are not listed here. */
export interface ProfilePlatformDataOther {
  _tag: string;
  [key: string]: unknown;
}

/** A pipeline stage on the team's board. A contact has at most one status. */
export interface Status {
  id: string;
  /** Unique within the team, ignoring case and accents. */
  name: string;
  /** Null when the status has no color. */
  color: string | null;
  createdAt: string;
}

/** A label the team puts on contacts. A contact can have several. */
export interface Tag {
  id: string;
  /** Unique within the team, ignoring case and accents. */
  name: string;
  /** A lowercase hex color. */
  color: string;
}

export type ContactsGetRequestExpandItem = "status" | "tags" | "assignee";

export interface ContactsGetRequest {
  contactId: Cuid2;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<ContactsGetRequestExpandItem>;
}

export interface ContactsUpdateRequest {
  contactId: Cuid2;
  /** A status, by ID or by name. Names match ignoring case and accents. When a value is one status's ID and another's name, the ID wins. */
  status?: string | null;
  notes?: string | null;
  valuation?: number | null;
  /** The default assignee of this contact's threads that have none of their own. */
  assigneeId?: Cuid2 | null;
}

export interface ContactsAddTagRequest {
  contactId: Cuid2;
  /** A tag, by ID or by name. Names match ignoring case and accents. When a value is one tag's ID and another's name, the ID wins. */
  tagRef: string;
}

export interface ContactsRemoveTagRequest {
  contactId: Cuid2;
  /** A tag, by ID or by name. Names match ignoring case and accents. When a value is one tag's ID and another's name, the ID wins. */
  tagRef: string;
}

/** Defaults to `inbox`, threads that are neither archived nor requests. `noReply` is the `inbox` threads whose latest activity is inbound. `requests` holds unarchived threads where `isRequest` is true. `archived` includes requests. `all` spans every folder. Every other filter narrows the folder. */
export type ThreadsListRequestFolder = "inbox" | "noReply" | "requests" | "archived" | "all";

/** Sort direction by inbox order: `activity.at`, or `createdAt` for a thread with no activity. A reminder or an accepted message request moves a thread up until its next message, without changing `activity.at`. Defaults to `desc`, newest first. */
export type ThreadsListRequestOrder = "desc" | "asc";

export type ThreadsListRequestExpandItem = "profile" | "contact" | "accountLink" | "assignee";

export interface ThreadsListRequest {
  /** Threads of these account links. Repeat the key to match any of several. */
  accountLinkId?: Array<Cuid2>;
  /** Repeat the key to match any of several. */
  platform?: Array<Platform>;
  /** Threads with these contacts. With `accountLinkId`, finds the thread between an account and a contact. Repeat the key to match any of several. */
  contactId?: Array<Cuid2>;
  /** Defaults to `inbox`, threads that are neither archived nor requests. `noReply` is the `inbox` threads whose latest activity is inbound. `requests` holds unarchived threads where `isRequest` is true. `archived` includes requests. `all` spans every folder. Every other filter narrows the folder. */
  folder?: ThreadsListRequestFolder;
  /** Threads whose contact has one of these tags. Repeat the key to match any of several. */
  tag?: Array<string>;
  /** Threads whose contact has one of these statuses. Repeat the key to match any of several. */
  status?: Array<string>;
  /** Threads whose `assigneeId`, the thread's own assignee or else its contact's, is one of these members. Repeat the key to match any of several. */
  assigneeId?: Array<Cuid2>;
  /** `true` keeps threads with no assignee, including through their contact. Not combinable with `assigneeId`. */
  unassigned?: boolean;
  /** Threads these campaigns sent a message in. Campaign sends archive the thread, so pair it with `folder=archived` or `all`. Repeat the key to match any of several. */
  campaignId?: Array<Cuid2>;
  /** Searches profile display names, usernames and the activity preview. Results follow `order`, not relevance. */
  q?: string;
  /** Sort direction by inbox order: `activity.at`, or `createdAt` for a thread with no activity. A reminder or an accepted message request moves a thread up until its next message, without changing `activity.at`. Defaults to `desc`, newest first. */
  order?: ThreadsListRequestOrder;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<ThreadsListRequestExpandItem>;
  /** Page size, from 1 to 100. Defaults to 50. */
  limit?: number;
  /** The previous page's `nextCursor`. Opaque, and valid only with the filters it was issued for. */
  cursor?: string;
}

/** In inbox order, newest first unless `order` is `asc`. */
export interface ThreadPage {
  data: Array<Thread>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

/** A conversation between one of the team's account links and one profile. */
export interface Thread {
  id: string;
  /** Always the platform of the thread's account link and profile. */
  platform: Platform;
  /** The conversation's ID on the platform. Null until the first message creates the conversation there. */
  platformId: string | null;
  /** An account link: a platform account the team connected to Inboxapp, the team's side of a conversation. */
  accountLinkId: string;
  /** A profile: one person's account on one platform. Not a contact ID. */
  profileId: string;
  /** A contact: the team's record of the person, with their status, tags, notes, valuation and default assignee. */
  contactId: string;
  /** The thread's own assignee, else its contact's default. */
  assigneeId: string | null;
  /** True while the conversation is an incoming request the account hasn't replied to or accepted. Requests are in the `requests` folder, not `inbox`. */
  isRequest: boolean;
  /** Whether the platform needs the account to accept the conversation before replying normally. `unknown` when the platform doesn't say. Independent of `isRequest`. */
  acceptanceState: ThreadAcceptanceState;
  archived: boolean;
  /** Marked unread in Inboxapp. A thread no one has opened yet is not unread. */
  unread: boolean;
  /** Capabilities the platform disables in this conversation, on top of the account link's `capabilities`. Using one fails with `threadRestricted`. */
  restrictions: Array<ThreadRestrictionsItem>;
  /** True while Inboxapp imports the conversation's older messages, so the message list may be incomplete. */
  syncing: boolean;
  /** Whether Inboxapp sends typing indicators to the platform while someone composes in this thread. `teamDefault` follows the team's setting. */
  typingIndicators: ThreadTypingIndicators;
  lastMessage: LastMessage | null;
  activity: ThreadActivity | null;
  createdAt: string;
  accountLink?: AccountLink;
  profile?: Profile;
  contact?: Contact;
  assignee?: Member;
}

/** Whether the platform needs the account to accept the conversation before replying normally. `unknown` when the platform doesn't say. Independent of `isRequest`. */
export type ThreadAcceptanceState = "required" | "notRequired" | "unknown" | (string & {});

export type ThreadRestrictionsItem =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

/** Whether Inboxapp sends typing indicators to the platform while someone composes in this thread. `teamDefault` follows the team's setting. */
export type ThreadTypingIndicators = "enabled" | "disabled" | "teamDefault" | (string & {});

/** The thread's latest message. Get it for its content. */
export interface LastMessage {
  id: string;
  /** `inbound` was received from the other side. `outbound` was sent by the account link. */
  direction: LastMessageDirection;
  createdAt: string;
}

/** `inbound` was received from the other side. `outbound` was sent by the account link. */
export type LastMessageDirection = "inbound" | "outbound" | (string & {});

/** The thread's latest activity: a message, or a reaction since. `at` is when it happened, which is not always the thread's position in a list: see `order`. */
export interface ThreadActivity {
  /** One line as the inbox shows it, such as the message text or `You reacted with 👍`. Null when there is nothing to show. */
  preview: string | null;
  /** `outbound` when the account link acted. */
  direction: ThreadActivityDirection;
  at: string;
}

/** `outbound` when the account link acted. */
export type ThreadActivityDirection = "inbound" | "outbound" | (string & {});

export type ThreadsGetRequestExpandItem = "profile" | "contact" | "accountLink" | "assignee";

export interface ThreadsGetRequest {
  threadId: Cuid2;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<ThreadsGetRequestExpandItem>;
}

/** Whether Inboxapp sends typing indicators to the platform while someone composes in this thread. `teamDefault` follows the team's setting. */
export type ThreadUpdateTypingIndicators = "enabled" | "disabled" | "teamDefault";

export interface ThreadsUpdateRequest {
  threadId: Cuid2;
  /** Also applied on the platform when the account link has `thread:archive:mutate`. */
  archived?: boolean;
  /** Also applied on the platform when the account link has `thread:read:mutate`. */
  unread?: boolean;
  /** The thread's own assignee. Null falls back to the contact's default. */
  assigneeId?: Cuid2 | null;
  /** Whether Inboxapp sends typing indicators to the platform while someone composes in this thread. `teamDefault` follows the team's setting. */
  typingIndicators?: ThreadUpdateTypingIndicators;
}

export interface ThreadsDeleteRequest {
  threadId: Cuid2;
}

export interface ThreadDeletion {
  /** `remoteAndLocal` when the conversation was also deleted on the platform. `local` when only Inboxapp's copy was, because the platform can't delete it or it never existed there. */
  scope: ThreadDeletionScope;
}

/** `remoteAndLocal` when the conversation was also deleted on the platform. `local` when only Inboxapp's copy was, because the platform can't delete it or it never existed there. */
export type ThreadDeletionScope = "remoteAndLocal" | "local" | (string & {});

export interface AccountLinkDisconnectedDetails {
  accountLinkId: string;
  /** `active` sends and syncs. `paused` is stopped for the reasons in `pauseReasons`, and resumes once none remain. `offline` lost its connection to the platform and must be reconnected in Inboxapp. */
  status: AccountLinkDisconnectedDetailsStatus;
}

/** `active` sends and syncs. `paused` is stopped for the reasons in `pauseReasons`, and resumes once none remain. `offline` lost its connection to the platform and must be reconnected in Inboxapp. */
export type AccountLinkDisconnectedDetailsStatus = "active" | "offline" | "paused" | (string & {});

export interface IntegrationSetupRequiredDetails {
  accountLinkId: string;
}

export interface CapabilityNotSupportedDetails {
  capability: CapabilityNotSupportedDetailsCapability;
}

export type CapabilityNotSupportedDetailsCapability =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

export interface PlatformRateLimitedDetails {
  retryAfterSeconds: number | null;
}

export interface PlatformUnavailableDetails {
  retryAfterSeconds: number | null;
}

export interface ThreadsTypingRequest {
  threadId: Cuid2;
}

export interface TypingSignal {
  status: TypingSignalStatus;
  /** Why it was skipped: `disabled` when `typingIndicators` is off for the thread, `rateLimited` when one was sent for the thread moments ago. Null when sent. */
  reason: TypingSignalReason | null;
}

export type TypingSignalStatus = "sent" | "skipped" | (string & {});

export type TypingSignalReason = "rateLimited" | "disabled" | (string & {});

/** Sort direction by `createdAt`. Defaults to `desc`, newest first. */
export type MessagesListRequestOrder = "desc" | "asc";

export type MessagesListRequestExpandItem =
  | "sentBy"
  | "reactions.author"
  | "thread"
  | "accountLink"
  | "replyTo.message";

export interface MessagesListRequest {
  threadId: Cuid2;
  /** Sort direction by `createdAt`. Defaults to `desc`, newest first. */
  order?: MessagesListRequestOrder;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<MessagesListRequestExpandItem>;
  /** Page size, from 1 to 100. Defaults to 50. */
  limit?: number;
  /** The previous page's `nextCursor`. Opaque, and valid only with the filters it was issued for. */
  cursor?: string;
}

/** Ordered by `createdAt`, newest first unless `order` is `asc`. */
export interface MessagePage {
  data: Array<Message>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

/** A message in a thread, sent or received by its account link. */
export interface Message {
  id: string;
  /** A thread: a conversation between one of the team's account links and one profile. */
  threadId: string;
  /** An account link: a platform account the team connected to Inboxapp, the team's side of a conversation. */
  accountLinkId: string;
  platform: Platform;
  /** Null when the platform assigned none. */
  platformId: string | null;
  /** `inbound` was received from the other side. `outbound` was sent by the account link. */
  direction: MessageDirection;
  /** Who on the team sent an outbound message. Null for inbound messages and for messages sent outside Inboxapp. */
  sentBy: MessageSentBy | null;
  /** The text as Inboxapp last saw it. A deleted message keeps its content. */
  content: string;
  entities: MessageEntities;
  /** Media, and at most one link card, told apart by `kind`. */
  attachments: Array<MessageAttachmentsItem>;
  /** Set when the message forwards another one, with the forwarded text as the sender's app declared it. Null otherwise. */
  forwarded: MessageForwarded | null;
  reactions: Array<Reaction>;
  /** When the message was last edited. Null when it hasn't been, or when the edit time wasn't recorded. Every version is in `GET /messages/{messageId}/history`. */
  editedAt: string | null;
  /** Set once the message was deleted for the account link or unsent for everyone. Deleted messages stay in lists, and `GET /messages/{messageId}/history` has the scope. */
  deletedAt: string | null;
  createdAt: string;
  platformData: MessagePlatformData;
  /** The message this one replies to. Null when it isn't a reply. */
  replyTo: MessageReplyTo | null;
  thread?: Thread;
  accountLink?: AccountLink;
}

/** `inbound` was received from the other side. `outbound` was sent by the account link. */
export type MessageDirection = "inbound" | "outbound" | (string & {});

/** Who on the team sent an outbound message. Null for inbound messages and for messages sent outside Inboxapp. */
export type MessageSentBy =
  | MessageSentByMember
  | MessageSentByAgent
  | MessageSentByCampaign
  | MessageSentByApi;

/** A team member sent it from Inboxapp. */
export interface MessageSentByMember {
  type: "member";
  /** A member: a person on the team. */
  memberId: string;
  member?: Member;
}

/** An agent the member authorized sent it, such as an MCP client. It acts with the member's access. */
export interface MessageSentByAgent {
  type: "agent";
  agentId: string;
  /** A member: a person on the team. */
  memberId: string;
  agent?: MessageSentByAgentAgent;
  member?: Member;
}

export interface MessageSentByAgentAgent {
  id: string;
  name: string;
}

/** A campaign sent it. */
export interface MessageSentByCampaign {
  type: "campaign";
  campaignId: string;
  /** The sequence step that sent it, possibly since removed. Null when no step was recorded. Not expandable. */
  stepId: string | null;
}

/** An API token sent it. `tokenId` is null on messages sent before tokens were recorded, and `token` is absent once the token is deleted. */
export interface MessageSentByApi {
  type: "api";
  tokenId: string | null;
  token?: MessageSentByApiToken;
}

export interface MessageSentByApiToken {
  id: string;
  name: string;
}

/** Parts of `content` the platform marked up. */
export interface MessageEntities {
  urls: Array<MessageEntitiesUrlsItem>;
  /** Platform posts shared in the message, such as a quoted post. */
  postShares: Array<MessageEntitiesPostSharesItem>;
  mentions: Array<MessageEntitiesMentionsItem>;
  hashtags: Array<MessageEntitiesHashtagsItem>;
  cashtags: Array<MessageEntitiesCashtagsItem>;
  /** Rich-text formatting. A `list` or `orderedList` spans its `listItem`s. */
  format: Array<MessageEntitiesFormatItem>;
}

export interface MessageEntitiesUrlsItem {
  url: string;
  displayUrl: string;
  /** Null when the platform gave no position. */
  indices: MessageEntitiesUrlsItemIndices | null;
}

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesUrlsItemIndices {
  start: number;
  end: number;
}

export interface MessageEntitiesPostSharesItem {
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string;
  url: string;
  /** Null when the platform gave no position. */
  indices: MessageEntitiesPostSharesItemIndices | null;
}

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesPostSharesItemIndices {
  start: number;
  end: number;
}

export interface MessageEntitiesMentionsItem {
  /** The platform username without its display prefix. Lookups take this form. */
  username: string;
  displayName: string | null;
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string | null;
  /** Null when the platform gave no position. */
  indices: MessageEntitiesMentionsItemIndices | null;
}

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesMentionsItemIndices {
  start: number;
  end: number;
}

export interface MessageEntitiesHashtagsItem {
  tag: string;
  /** Null when the platform gave no position. */
  indices: MessageEntitiesHashtagsItemIndices | null;
}

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesHashtagsItemIndices {
  start: number;
  end: number;
}

export interface MessageEntitiesCashtagsItem {
  symbol: string;
  /** Null when the platform gave no position. */
  indices: MessageEntitiesCashtagsItemIndices | null;
}

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesCashtagsItemIndices {
  start: number;
  end: number;
}

export interface MessageEntitiesFormatItem {
  kind: MessageEntitiesFormatItemKind;
  /** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
  indices: MessageEntitiesFormatItemIndices;
}

export type MessageEntitiesFormatItemKind =
  | "bold"
  | "list"
  | "orderedList"
  | "listItem"
  | (string & {});

/** Offsets into `content` in Unicode code points, end-exclusive. A JavaScript client slices `Array.from(content)`, not `content`. */
export interface MessageEntitiesFormatItemIndices {
  start: number;
  end: number;
}

export type MessageAttachmentsItem = AttachmentMedia | AttachmentCard;

/** An image, GIF, video, audio clip or file. Its `url` expires, so fetch it again when needed. */
export interface AttachmentMedia {
  /** The attachment's stable position in `attachments`, which `GET /messages/{messageId}/attachments/{index}` takes. */
  index: number;
  kind: AttachmentMediaKind;
  filename: string | null;
  contentType: string | null;
  sizeBytes: number | null;
  width: number | null;
  height: number | null;
  /** Width divided by height. */
  aspectRatio: number | null;
  /** Video and audio only. */
  durationSeconds: number | null;
  /** `ready` once `url` is usable. `pending` and `processing` while Inboxapp stores a copy: resolve the attachment again later. `failed` when Inboxapp gave up. */
  status: AttachmentMediaStatus;
  /** Set exactly when `status` is `ready`. */
  url: string | null;
  /** When `url` stops working. Null for URLs that don't expire. Get a fresh URL from `GET /messages/{messageId}/attachments/{index}`. */
  expiresAt: string | null;
  /** The still frame shown before a video plays. Video only, and only once usable. */
  poster: AttachmentMediaPoster | null;
}

export type AttachmentMediaKind = "image" | "gif" | "video" | "audio" | "file" | (string & {});

/** `ready` once `url` is usable. `pending` and `processing` while Inboxapp stores a copy: resolve the attachment again later. `failed` when Inboxapp gave up. */
export type AttachmentMediaStatus = "ready" | "pending" | "processing" | "failed" | (string & {});

export interface AttachmentMediaPoster {
  url: string;
  /** When `url` stops working. Null for URLs that don't expire. Get a fresh URL from `GET /messages/{messageId}/attachments/{index}`. */
  expiresAt: string | null;
  width: number | null;
  height: number | null;
}

/** The preview of a link in the message. A message has at most one. */
export interface AttachmentCard {
  /** The attachment's stable position in `attachments`, which `GET /messages/{messageId}/attachments/{index}` takes. */
  index: number;
  kind: "card";
  url: string;
  title: string | null;
  description: string | null;
  domain: string | null;
  thumbnail: AttachmentCardThumbnail | null;
}

export interface AttachmentCardThumbnail {
  url: string;
  width: number;
  height: number;
  alt: string | null;
}

export interface MessageForwarded {
  content: string | null;
}

export interface Reaction {
  emoji: string;
  author: ReactionAuthor;
  /** Null when the platform reports no time. */
  createdAt: string | null;
}

export type ReactionAuthor =
  | ReactionAuthorAccountLink
  | ReactionAuthorProfile
  | ReactionAuthorUnknown;

/** The team's account link reacted. */
export interface ReactionAuthorAccountLink {
  type: "accountLink";
  /** An account link: a platform account the team connected to Inboxapp, the team's side of a conversation. */
  accountLinkId: string;
  accountLink?: AccountLink;
}

/** The other side of the conversation reacted. */
export interface ReactionAuthorProfile {
  type: "profile";
  /** A profile: one person's account on one platform. Not a contact ID. */
  profileId: string;
  /** Null when the profile has no contact in the team. */
  contactId: string | null;
  profile?: Profile;
  contact?: Contact;
}

/** Someone Inboxapp can't match to the account link or the thread's profile, such as another member of a group conversation. Expands to nothing. */
export interface ReactionAuthorUnknown {
  type: "unknown";
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string;
}

/** Fields only one platform has, tagged by `_tag`. Ignore tags you don't know. */
export type MessagePlatformData = MessagePlatformDataTwitter | MessagePlatformDataOther;

export interface MessagePlatformDataTwitter {
  _tag: "twitter";
  /** An end-to-end encrypted X Chat message. */
  encrypted: boolean;
}

/** A platform the team has enabled beyond those every team can use. Its fields are not listed here. */
export interface MessagePlatformDataOther {
  _tag: string;
  [key: string]: unknown;
}

export interface MessageReplyTo {
  /** Null when Inboxapp has no copy of the quoted message in this thread. */
  messageId: string | null;
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string | null;
  /** The quoted text as captured at reply time. */
  content: string;
  /** The quoted sender's display name, from the platform. */
  authorName: string | null;
  message?: Message;
}

export type MessagesGetRequestExpandItem =
  | "sentBy"
  | "reactions.author"
  | "thread"
  | "accountLink"
  | "replyTo.message";

export interface MessagesGetRequest {
  messageId: Cuid2;
  /** Related resources to embed next to their ID field, one path per key, at most 4. */
  expand?: Array<MessagesGetRequestExpandItem>;
}

export interface MessagesEditRequest {
  messageId: Cuid2;
  content: string;
}

export interface ThreadRestrictedDetails {
  capability: ThreadRestrictedDetailsCapability;
}

export type ThreadRestrictedDetailsCapability =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

export interface MutationWindowClosedDetails {
  capability: MutationWindowClosedDetailsCapability;
  closedAt: string | null;
}

export type MutationWindowClosedDetailsCapability =
  | "message:send"
  | "message:edit"
  | "message:delete:self"
  | "message:unsend"
  | "message:react"
  | "message:reply"
  | "message:forward"
  | "media:image"
  | "media:video"
  | "media:gif"
  | "media:file"
  | "media:audio"
  | "thread:typing:send"
  | "thread:typing:receive"
  | "thread:message-requests"
  | "thread:delete:remote"
  | "directory:typeahead"
  | "thread:archive:observe"
  | "thread:archive:mutate"
  | "thread:read:observe"
  | "thread:read:mutate"
  | "profile:follow"
  | "profile:unfollow"
  | (string & {});

export interface MessageNotModifiableDetails {
  reason: string;
}

export interface ContentRejectedDetails {
  detail: string;
}

/** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
export type MessagesUnsendRequestScope = "self" | "all";

export interface MessagesUnsendRequest {
  messageId: Cuid2;
  /** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
  scope: MessagesUnsendRequestScope;
}

export interface MessageDeletion {
  messageId: string;
  /** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
  scope: MessageDeletionScope;
  deletedAt: string;
}

/** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
export type MessageDeletionScope = "self" | "all" | (string & {});

export type SendRequestTarget =
  | SendRequestTargetThread
  | SendRequestTargetContact
  | SendRequestTargetProfile;

/** An existing thread. */
export interface SendRequestTargetThread {
  type: "thread";
  threadId: Cuid2;
}

/** The contact's profile on the account link's platform, in its existing thread or a new one. Fails with `recipientUnavailable` when the contact has none there, and `profileAmbiguous` when it has several. */
export interface SendRequestTargetContact {
  type: "contact";
  /** The account link to send from. */
  accountLinkId: Cuid2;
  contactId: Cuid2;
}

/** A platform user, in its existing thread or a new one. Without the Advanced API add-on, the profile must already belong to one of the team's contacts. */
export interface SendRequestTargetProfile {
  type: "profile";
  /** The account link to send from. */
  accountLinkId: Cuid2;
  /** Must be the account link's platform. */
  platform: Platform;
  /** The ID the platform gives this object. Only meaningful next to its `platform`. */
  platformId: string;
}

export interface MessagesSendRequest {
  /** Makes retries safe: a replay with the same key and body returns the original message. Scoped to the team. */
  idempotencyKey?: string;
  target: SendRequestTarget;
  /** Up to the platform's `limits.characters`. Longer content fails with `contentRejected`. */
  content: string;
  /** A message in the thread this send lands in, to reply to. */
  replyToMessageId?: Cuid2;
}

export interface PlanRequiredDetails {
  feature: string;
}

export interface SendInProgressDetails {
  messageId: string;
}

export interface RecipientUnavailableDetails {
  reason: string;
}

export interface PlatformNotSupportedDetails {
  platform: Platform;
  supported: Array<Platform>;
}

export interface ProfileAmbiguousDetails {
  contactId: string;
  platform: Platform;
}

export interface SendUnconfirmedDetails {
  messageId: string;
}

export interface MessagesHistoryRequest {
  messageId: Cuid2;
}

export interface MessageHistory {
  /** The original first, at the message's `createdAt`, then each edit. */
  versions: Array<MessageHistoryVersionsItem>;
  /** Null while the message isn't deleted. */
  deletion: MessageHistoryDeletion | null;
  /** Whether edit and deletion times come from the platform, or are when Inboxapp noticed the change. */
  times: MessageHistoryTimes;
}

export interface MessageHistoryVersionsItem {
  content: string;
  createdAt: string;
  /** Where the change was made: `inbox` in the app, `api` through this API, `platform` directly on the platform. Null on older records. */
  origin: MessageHistoryVersionsItemOrigin | null;
}

export type MessageHistoryVersionsItemOrigin = "inbox" | "platform" | "api" | (string & {});

export interface MessageHistoryDeletion {
  deletedAt: string;
  /** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
  scope: MessageHistoryDeletionScope;
  /** Where the change was made: `inbox` in the app, `api` through this API, `platform` directly on the platform. Null on older records. */
  origin: MessageHistoryDeletionOrigin | null;
}

/** `self` deletes for the account link only, which needs `message:delete:self`. `all` unsends for every participant, which needs `message:unsend`. */
export type MessageHistoryDeletionScope = "self" | "all" | (string & {});

export type MessageHistoryDeletionOrigin = "inbox" | "platform" | "api" | (string & {});

/** Whether edit and deletion times come from the platform, or are when Inboxapp noticed the change. */
export type MessageHistoryTimes = "platform" | "observed" | (string & {});

export interface MessagesReactRequest {
  messageId: Cuid2;
  /** Exactly one emoji. */
  emoji: string;
}

export interface Reactions {
  reactions: Array<Reaction>;
  version: number;
}

export interface MessagesUnreactRequest {
  messageId: Cuid2;
  /** Exactly one emoji. */
  emoji: string;
}

export interface MessagesAttachmentRequest {
  messageId: Cuid2;
  index: number;
}

export interface TagsListRequest {}

/** Every tag, ordered by `name`, in one page. */
export interface TagPage {
  data: Array<Tag>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

export interface TagsCreateRequest {
  name: string;
  /** A color name from `GET /colors`, case-insensitive, or a 6-digit hex value. Stored as hex. Defaults to a random color from `GET /colors`. */
  color?: string;
}

export interface NameTakenDetails {
  name: string;
}

export interface TagLimitReachedDetails {
  max: number;
}

export interface TagsGetRequest {
  /** A tag, by ID or by name. Names match ignoring case and accents. When a value is one tag's ID and another's name, the ID wins. */
  tagRef: string;
}

export interface TagsUpdateRequest {
  /** A tag, by ID or by name. Names match ignoring case and accents. When a value is one tag's ID and another's name, the ID wins. */
  tagRef: string;
  name?: string;
  /** A color name from `GET /colors`, case-insensitive, or a 6-digit hex value. Stored as hex. */
  color?: string;
}

export interface TagsDeleteRequest {
  /** A tag, by ID or by name. Names match ignoring case and accents. When a value is one tag's ID and another's name, the ID wins. */
  tagRef: string;
}

export interface StatusesListRequest {}

/** Every status, in board order, in one page. */
export interface StatusPage {
  data: Array<Status>;
  /** Pass it back as `cursor`, with the same filters, to read the next page. Null on the last page. */
  nextCursor: string | null;
}

export interface StatusesCreateRequest {
  name: string;
  /** Null for no color. */
  color?: string | null;
}

export interface StatusesGetRequest {
  /** A status, by ID or by name. Names match ignoring case and accents. When a value is one status's ID and another's name, the ID wins. */
  statusRef: string;
}

export interface StatusesUpdateRequest {
  /** A status, by ID or by name. Names match ignoring case and accents. When a value is one status's ID and another's name, the ID wins. */
  statusRef: string;
  name?: string;
  /** Null for no color. */
  color?: string | null;
}

export interface StatusesDeleteRequest {
  /** A status, by ID or by name. Names match ignoring case and accents. When a value is one status's ID and another's name, the ID wins. */
  statusRef: string;
}

export interface ColorsListRequest {}

/** A color from Inboxapp's palette, for tags and statuses, which `GET /colors` lists. */
export interface Color {
  name: string;
  /** A lowercase hex color. */
  hex: string;
}

export type EventsListRequestTypeItem =
  | "thread.created"
  | "thread.deleted"
  | "thread.assigned"
  | "thread.unassigned"
  | "thread.archived"
  | "thread.unarchived"
  | "thread.typing"
  | "message.sent"
  | "message.received"
  | "message.edited"
  | "message.deleted"
  | "message.reactionAdded"
  | "message.reactionRemoved"
  | "contact.statusChanged"
  | "contact.tagsChanged"
  | "contact.notesChanged"
  | "contact.valuationChanged"
  | "contact.assigneeChanged"
  | "tag.created"
  | "tag.updated"
  | "tag.deleted"
  | "status.created"
  | "status.updated"
  | "status.deleted"
  | "campaign.created"
  | "campaign.started"
  | "campaign.paused"
  | "campaign.resumed"
  | "campaign.completed"
  | "target.contacted"
  | "target.followUpSent"
  | "target.replied";

export interface EventsListRequest {
  /** Exclusive. A webhook's `seq` resumes right after it. Omit to start at the oldest retained event. */
  afterSeq?: number;
  /** Only these event types. Repeat the key to match any of several. */
  type?: Array<EventsListRequestTypeItem>;
  /** Events to read, from 1 to 1000. Defaults to 100. */
  limit?: number;
}

export interface EventPage {
  data: Array<EventPageDataItem>;
  /** The last sequence number read, including events this page leaves out. Null when nothing was read. Pass it as `afterSeq` to continue. */
  lastSeq: number | null;
  hasMore: boolean;
}

export type EventPageDataItem =
  | ThreadCreatedEvent
  | ThreadDeletedEvent
  | ThreadAssignedEvent
  | ThreadUnassignedEvent
  | ThreadArchivedEvent
  | ThreadUnarchivedEvent
  | ThreadTypingEvent
  | MessageSentEvent
  | MessageReceivedEvent
  | MessageEditedEvent
  | MessageDeletedEvent
  | MessageReactionAddedEvent
  | MessageReactionRemovedEvent
  | ContactStatusChangedEvent
  | ContactTagsChangedEvent
  | ContactNotesChangedEvent
  | ContactValuationChangedEvent
  | ContactAssigneeChangedEvent
  | TagCreatedEvent
  | TagUpdatedEvent
  | TagDeletedEvent
  | StatusCreatedEvent
  | StatusUpdatedEvent
  | StatusDeletedEvent
  | CampaignCreatedEvent
  | CampaignStartedEvent
  | CampaignPausedEvent
  | CampaignResumedEvent
  | CampaignCompletedEvent
  | TargetContactedEvent
  | TargetFollowUpSentEvent
  | TargetRepliedEvent;

export interface ThreadCreatedEvent {
  id: string;
  seq: number;
  type: "thread.created";
  apiVersion: "2";
  createdAt: string;
  object: ThreadCreatedEventObject;
  data: unknown;
}

export interface ThreadCreatedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadDeletedEvent {
  id: string;
  seq: number;
  type: "thread.deleted";
  apiVersion: "2";
  createdAt: string;
  object: ThreadDeletedEventObject;
  data: ThreadDeletedEventData;
}

export interface ThreadDeletedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadDeletedEventData {
  accountLinkId: string;
  platform: Platform;
}

export interface ThreadAssignedEvent {
  id: string;
  seq: number;
  type: "thread.assigned";
  apiVersion: "2";
  createdAt: string;
  object: ThreadAssignedEventObject;
  data: ThreadAssignedEventData;
}

export interface ThreadAssignedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadAssignedEventData {
  assigneeId: string | null;
}

export interface ThreadUnassignedEvent {
  id: string;
  seq: number;
  type: "thread.unassigned";
  apiVersion: "2";
  createdAt: string;
  object: ThreadUnassignedEventObject;
  data: ThreadUnassignedEventData;
}

export interface ThreadUnassignedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadUnassignedEventData {
  assigneeId: string | null;
}

export interface ThreadArchivedEvent {
  id: string;
  seq: number;
  type: "thread.archived";
  apiVersion: "2";
  createdAt: string;
  object: ThreadArchivedEventObject;
  data: unknown;
}

export interface ThreadArchivedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadUnarchivedEvent {
  id: string;
  seq: number;
  type: "thread.unarchived";
  apiVersion: "2";
  createdAt: string;
  object: ThreadUnarchivedEventObject;
  data: unknown;
}

export interface ThreadUnarchivedEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ThreadTypingEvent {
  id: string;
  seq: number;
  type: "thread.typing";
  apiVersion: "2";
  createdAt: string;
  object: ThreadTypingEventObject;
  data: unknown;
}

export interface ThreadTypingEventObject {
  type: "thread";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageSentEvent {
  id: string;
  seq: number;
  type: "message.sent";
  apiVersion: "2";
  createdAt: string;
  object: MessageSentEventObject;
  data: MessageSentEventData;
}

export interface MessageSentEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageSentEventData {
  threadId: string;
}

export interface MessageReceivedEvent {
  id: string;
  seq: number;
  type: "message.received";
  apiVersion: "2";
  createdAt: string;
  object: MessageReceivedEventObject;
  data: MessageReceivedEventData;
}

export interface MessageReceivedEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageReceivedEventData {
  threadId: string;
}

export interface MessageEditedEvent {
  id: string;
  seq: number;
  type: "message.edited";
  apiVersion: "2";
  createdAt: string;
  object: MessageEditedEventObject;
  data: MessageEditedEventData;
}

export interface MessageEditedEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageEditedEventData {
  threadId: string;
}

export interface MessageDeletedEvent {
  id: string;
  seq: number;
  type: "message.deleted";
  apiVersion: "2";
  createdAt: string;
  object: MessageDeletedEventObject;
  data: MessageDeletedEventData;
}

export interface MessageDeletedEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageDeletedEventData {
  threadId: string;
  scope: MessageDeletedEventDataScope;
}

export type MessageDeletedEventDataScope = "self" | "all" | (string & {});

export interface MessageReactionAddedEvent {
  id: string;
  seq: number;
  type: "message.reactionAdded";
  apiVersion: "2";
  createdAt: string;
  object: MessageReactionAddedEventObject;
  data: MessageReactionAddedEventData;
}

export interface MessageReactionAddedEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageReactionAddedEventData {
  threadId: string;
  emoji: string;
  authorPlatformId: string;
}

export interface MessageReactionRemovedEvent {
  id: string;
  seq: number;
  type: "message.reactionRemoved";
  apiVersion: "2";
  createdAt: string;
  object: MessageReactionRemovedEventObject;
  data: MessageReactionRemovedEventData;
}

export interface MessageReactionRemovedEventObject {
  type: "message";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface MessageReactionRemovedEventData {
  threadId: string;
  emoji: string;
  authorPlatformId: string;
}

export interface ContactStatusChangedEvent {
  id: string;
  seq: number;
  type: "contact.statusChanged";
  apiVersion: "2";
  createdAt: string;
  object: ContactStatusChangedEventObject;
  data: ContactStatusChangedEventData;
}

export interface ContactStatusChangedEventObject {
  type: "contact";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ContactStatusChangedEventData {
  statusId: string | null;
}

export interface ContactTagsChangedEvent {
  id: string;
  seq: number;
  type: "contact.tagsChanged";
  apiVersion: "2";
  createdAt: string;
  object: ContactTagsChangedEventObject;
  data: ContactTagsChangedEventData;
}

export interface ContactTagsChangedEventObject {
  type: "contact";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ContactTagsChangedEventData {
  tagIds: Array<string>;
}

export interface ContactNotesChangedEvent {
  id: string;
  seq: number;
  type: "contact.notesChanged";
  apiVersion: "2";
  createdAt: string;
  object: ContactNotesChangedEventObject;
  data: ContactNotesChangedEventData;
}

export interface ContactNotesChangedEventObject {
  type: "contact";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ContactNotesChangedEventData {
  notes: string | null;
}

export interface ContactValuationChangedEvent {
  id: string;
  seq: number;
  type: "contact.valuationChanged";
  apiVersion: "2";
  createdAt: string;
  object: ContactValuationChangedEventObject;
  data: ContactValuationChangedEventData;
}

export interface ContactValuationChangedEventObject {
  type: "contact";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ContactValuationChangedEventData {
  valuation: number | null;
}

export interface ContactAssigneeChangedEvent {
  id: string;
  seq: number;
  type: "contact.assigneeChanged";
  apiVersion: "2";
  createdAt: string;
  object: ContactAssigneeChangedEventObject;
  data: ContactAssigneeChangedEventData;
}

export interface ContactAssigneeChangedEventObject {
  type: "contact";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface ContactAssigneeChangedEventData {
  assigneeId: string | null;
}

export interface TagCreatedEvent {
  id: string;
  seq: number;
  type: "tag.created";
  apiVersion: "2";
  createdAt: string;
  object: TagCreatedEventObject;
  data: unknown;
}

export interface TagCreatedEventObject {
  type: "tag";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TagUpdatedEvent {
  id: string;
  seq: number;
  type: "tag.updated";
  apiVersion: "2";
  createdAt: string;
  object: TagUpdatedEventObject;
  data: unknown;
}

export interface TagUpdatedEventObject {
  type: "tag";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TagDeletedEvent {
  id: string;
  seq: number;
  type: "tag.deleted";
  apiVersion: "2";
  createdAt: string;
  object: TagDeletedEventObject;
  data: unknown;
}

export interface TagDeletedEventObject {
  type: "tag";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface StatusCreatedEvent {
  id: string;
  seq: number;
  type: "status.created";
  apiVersion: "2";
  createdAt: string;
  object: StatusCreatedEventObject;
  data: unknown;
}

export interface StatusCreatedEventObject {
  type: "status";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface StatusUpdatedEvent {
  id: string;
  seq: number;
  type: "status.updated";
  apiVersion: "2";
  createdAt: string;
  object: StatusUpdatedEventObject;
  data: unknown;
}

export interface StatusUpdatedEventObject {
  type: "status";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface StatusDeletedEvent {
  id: string;
  seq: number;
  type: "status.deleted";
  apiVersion: "2";
  createdAt: string;
  object: StatusDeletedEventObject;
  data: unknown;
}

export interface StatusDeletedEventObject {
  type: "status";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface CampaignCreatedEvent {
  id: string;
  seq: number;
  type: "campaign.created";
  apiVersion: "2";
  createdAt: string;
  object: CampaignCreatedEventObject;
  data: unknown;
}

export interface CampaignCreatedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface CampaignStartedEvent {
  id: string;
  seq: number;
  type: "campaign.started";
  apiVersion: "2";
  createdAt: string;
  object: CampaignStartedEventObject;
  data: unknown;
}

export interface CampaignStartedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface CampaignPausedEvent {
  id: string;
  seq: number;
  type: "campaign.paused";
  apiVersion: "2";
  createdAt: string;
  object: CampaignPausedEventObject;
  data: unknown;
}

export interface CampaignPausedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface CampaignResumedEvent {
  id: string;
  seq: number;
  type: "campaign.resumed";
  apiVersion: "2";
  createdAt: string;
  object: CampaignResumedEventObject;
  data: unknown;
}

export interface CampaignResumedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface CampaignCompletedEvent {
  id: string;
  seq: number;
  type: "campaign.completed";
  apiVersion: "2";
  createdAt: string;
  object: CampaignCompletedEventObject;
  data: unknown;
}

export interface CampaignCompletedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TargetContactedEvent {
  id: string;
  seq: number;
  type: "target.contacted";
  apiVersion: "2";
  createdAt: string;
  object: TargetContactedEventObject;
  data: TargetContactedEventData;
}

export interface TargetContactedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TargetContactedEventData {
  threadId: string;
  messageId: string;
  contactId: string | null;
  stepNumber: number | null;
}

export interface TargetFollowUpSentEvent {
  id: string;
  seq: number;
  type: "target.followUpSent";
  apiVersion: "2";
  createdAt: string;
  object: TargetFollowUpSentEventObject;
  data: TargetFollowUpSentEventData;
}

export interface TargetFollowUpSentEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TargetFollowUpSentEventData {
  threadId: string;
  messageId: string;
  contactId: string | null;
  stepNumber: number | null;
}

export interface TargetRepliedEvent {
  id: string;
  seq: number;
  type: "target.replied";
  apiVersion: "2";
  createdAt: string;
  object: TargetRepliedEventObject;
  data: TargetRepliedEventData;
}

export interface TargetRepliedEventObject {
  type: "campaign";
  id: string;
  /** The object's path under the API; 404 once it's deleted. */
  url: string;
}

export interface TargetRepliedEventData {
  threadId: string;
  messageId: string;
  contactId: string | null;
  stepNumber: number | null;
}

export interface MessagesSendResponse {
  message: Message;
  /** The thread the message landed in, which a concurrent send may have created. Adopt it. */
  thread: Thread;
  /** `201` for a new send, `200` for a replay of an `Idempotency-Key`. */
  httpStatus: number;
}
