// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as T from "./types.ts";

/** Every webhook event, by its `type`. */
export interface WebhookEvents {
  "thread.created": T.ThreadCreatedEvent;
  "thread.deleted": T.ThreadDeletedEvent;
  "thread.assigned": T.ThreadAssignedEvent;
  "thread.unassigned": T.ThreadUnassignedEvent;
  "thread.archived": T.ThreadArchivedEvent;
  "thread.unarchived": T.ThreadUnarchivedEvent;
  "thread.typing": T.ThreadTypingEvent;
  "message.sent": T.MessageSentEvent;
  "message.received": T.MessageReceivedEvent;
  "message.edited": T.MessageEditedEvent;
  "message.deleted": T.MessageDeletedEvent;
  "message.reactionAdded": T.MessageReactionAddedEvent;
  "message.reactionRemoved": T.MessageReactionRemovedEvent;
  "contact.statusChanged": T.ContactStatusChangedEvent;
  "contact.tagsChanged": T.ContactTagsChangedEvent;
  "contact.notesChanged": T.ContactNotesChangedEvent;
  "contact.valuationChanged": T.ContactValuationChangedEvent;
  "contact.assigneeChanged": T.ContactAssigneeChangedEvent;
  "tag.created": T.TagCreatedEvent;
  "tag.updated": T.TagUpdatedEvent;
  "tag.deleted": T.TagDeletedEvent;
  "status.created": T.StatusCreatedEvent;
  "status.updated": T.StatusUpdatedEvent;
  "status.deleted": T.StatusDeletedEvent;
  "campaign.created": T.CampaignCreatedEvent;
  "campaign.started": T.CampaignStartedEvent;
  "campaign.paused": T.CampaignPausedEvent;
  "campaign.resumed": T.CampaignResumedEvent;
  "campaign.completed": T.CampaignCompletedEvent;
  "target.contacted": T.TargetContactedEvent;
  "target.followUpSent": T.TargetFollowUpSentEvent;
  "target.replied": T.TargetRepliedEvent;
}

export type WebhookEventType = keyof WebhookEvents;

export type WebhookEvent = WebhookEvents[WebhookEventType];

export const webhookEventTypes = [
  "thread.created",
  "thread.deleted",
  "thread.assigned",
  "thread.unassigned",
  "thread.archived",
  "thread.unarchived",
  "thread.typing",
  "message.sent",
  "message.received",
  "message.edited",
  "message.deleted",
  "message.reactionAdded",
  "message.reactionRemoved",
  "contact.statusChanged",
  "contact.tagsChanged",
  "contact.notesChanged",
  "contact.valuationChanged",
  "contact.assigneeChanged",
  "tag.created",
  "tag.updated",
  "tag.deleted",
  "status.created",
  "status.updated",
  "status.deleted",
  "campaign.created",
  "campaign.started",
  "campaign.paused",
  "campaign.resumed",
  "campaign.completed",
  "target.contacted",
  "target.followUpSent",
  "target.replied",
] as const satisfies ReadonlyArray<WebhookEventType>;
