// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.AccountLinksListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: S.optional(S.Array(Model.Platform)).pipe(T.Query("platform")),
    status: S.optional(S.Array(Model.AccountLinksListRequestStatusItem)).pipe(T.Query("status")),
    limit: S.optional(S.Number).pipe(T.Query("limit")),
    cursor: S.optional(S.String).pipe(T.Query("cursor")),
  }).pipe(T.Http({ method: "GET", uri: "/account-links", code: 200 })),
).annotate({ identifier: "AccountLinksListRequest" }) as any as S.Schema<M.AccountLinksListRequest>;

export type ListError = E.InvalidCursor | E.PlatformNotAvailable | InboxappOpError;
/** List account links */
export const list: API.PaginatedOperationMethod<
  M.AccountLinksListRequest,
  M.AccountLinkPage,
  ListError,
  InboxappOpContext,
  M.AccountLink
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "accountLinks.list",
  input: ListRequest,
  output: Model.AccountLinkPage,
  errors: [E.InvalidCursor, E.PlatformNotAvailable],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
}));

export type GetRequest = M.AccountLinksGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountLinkId: Model.Cuid2.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/account-links/{accountLinkId}", code: 200 })),
).annotate({ identifier: "AccountLinksGetRequest" }) as any as S.Schema<M.AccountLinksGetRequest>;

export type GetError = E.PlatformNotAvailable | E.AccountLinkNotFound | InboxappOpError;
/** Get account link */
export const get: API.OperationMethod<
  M.AccountLinksGetRequest,
  M.AccountLink,
  GetError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "accountLinks.get",
  input: GetRequest,
  output: Model.AccountLink,
  errors: [E.PlatformNotAvailable, E.AccountLinkNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
