// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.ColorsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/colors", code: 200 })),
).annotate({ identifier: "ColorsListRequest" }) as any as S.Schema<M.ColorsListRequest>;

export type ListError = InboxappOpError;
/** List colors */
export const list: API.OperationMethod<
  M.ColorsListRequest,
  Array<M.Color>,
  ListError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "colors.list",
  input: ListRequest,
  output: S.Array(Model.Color),
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
