// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.ContactsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: Model.Platform.pipe(T.Query("platform")),
    platformId: S.optional(S.Array(S.String)).pipe(T.Query("platformId")),
    username: S.optional(S.Array(S.String)).pipe(T.Query("username")),
    expand: S.optional(S.Array(Model.ContactsListRequestExpandItem)).pipe(T.Query("expand")),
    limit: S.optional(S.Number).pipe(T.Query("limit")),
    cursor: S.optional(S.String).pipe(T.Query("cursor")),
  }).pipe(T.Http({ method: "GET", uri: "/contacts", code: 200 })),
).annotate({ identifier: "ContactsListRequest" }) as any as S.Schema<M.ContactsListRequest>;

export type ListError = E.InvalidCursor | E.PlatformNotAvailable | InboxappOpError;
/**
 * Find contacts
 *
 * Finds contacts by the platform identity of one of their profiles: a `platform` with `platformId` or `username`.
 */
export const list: API.PaginatedOperationMethod<
  M.ContactsListRequest,
  M.ContactPage,
  ListError,
  InboxappOpContext,
  M.Contact
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "contacts.list",
  input: ListRequest,
  output: Model.ContactPage,
  errors: [E.InvalidCursor, E.PlatformNotAvailable],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
}));

export type GetRequest = M.ContactsGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contactId: Model.Cuid2.pipe(T.Label()),
    expand: S.optional(S.Array(Model.ContactsGetRequestExpandItem)).pipe(T.Query("expand")),
  }).pipe(T.Http({ method: "GET", uri: "/contacts/{contactId}", code: 200 })),
).annotate({ identifier: "ContactsGetRequest" }) as any as S.Schema<M.ContactsGetRequest>;

export type GetError = E.PlatformNotAvailable | E.ContactNotFound | InboxappOpError;
/** Get contact */
export const get: API.OperationMethod<
  M.ContactsGetRequest,
  M.Contact,
  GetError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "contacts.get",
  input: GetRequest,
  output: Model.Contact,
  errors: [E.PlatformNotAvailable, E.ContactNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type UpdateRequest = M.ContactsUpdateRequest;
export const UpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contactId: Model.Cuid2.pipe(T.Label()),
    status: S.optional(S.NullOr(S.String)),
    notes: S.optional(S.NullOr(S.String)),
    valuation: S.optional(S.NullOr(S.Number)),
    assigneeId: S.optional(S.NullOr(Model.Cuid2)),
  }).pipe(T.Http({ method: "PATCH", uri: "/contacts/{contactId}", code: 200 })),
).annotate({ identifier: "ContactsUpdateRequest" }) as any as S.Schema<M.ContactsUpdateRequest>;

export type UpdateError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ContactNotFound
  | InboxappOpError;
/** Update contact */
export const update: API.OperationMethod<
  M.ContactsUpdateRequest,
  M.Contact,
  UpdateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "contacts.update",
  input: UpdateRequest,
  output: Model.Contact,
  errors: [E.PlatformNotAvailable, E.WorkspaceLocked, E.ContactNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type AddTagRequest = M.ContactsAddTagRequest;
export const AddTagRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contactId: Model.Cuid2.pipe(T.Label()),
    tagRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "PUT", uri: "/contacts/{contactId}/tags/{tagRef}", code: 204 })),
).annotate({ identifier: "ContactsAddTagRequest" }) as any as S.Schema<M.ContactsAddTagRequest>;

export type AddTagError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ContactNotFound
  | E.TagNotFound
  | InboxappOpError;
/**
 * Add tag to contact
 *
 * Adding a tag the contact already has succeeds.
 */
export const addTag: API.OperationMethod<
  M.ContactsAddTagRequest,
  void,
  AddTagError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "contacts.addTag",
  input: AddTagRequest,
  errors: [E.PlatformNotAvailable, E.WorkspaceLocked, E.ContactNotFound, E.TagNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type RemoveTagRequest = M.ContactsRemoveTagRequest;
export const RemoveTagRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contactId: Model.Cuid2.pipe(T.Label()),
    tagRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/contacts/{contactId}/tags/{tagRef}", code: 204 })),
).annotate({
  identifier: "ContactsRemoveTagRequest",
}) as any as S.Schema<M.ContactsRemoveTagRequest>;

export type RemoveTagError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ContactNotFound
  | E.TagNotFound
  | InboxappOpError;
/**
 * Remove tag from contact
 *
 * Removing a tag the contact doesn't have succeeds.
 */
export const removeTag: API.OperationMethod<
  M.ContactsRemoveTagRequest,
  void,
  RemoveTagError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "contacts.removeTag",
  input: RemoveTagRequest,
  errors: [E.PlatformNotAvailable, E.WorkspaceLocked, E.ContactNotFound, E.TagNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
