// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import * as Schema from "effect/Schema";
import type * as M from "../../services/types.ts";
import * as Category from "../category.ts";
import { Details, DurationSchema } from "../errors.ts";
import * as T from "../traits.ts";

/** `400 invalidRequest` */
export class InvalidRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<InvalidRequest>()("InvalidRequest", {
      code: Schema.Literal("invalidRequest"),
      message: Schema.String,
      details: Details<M.InvalidRequestDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "invalidRequest" }],
  ) {}

/** `401 unauthorized` */
export class Unauthorized
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<Unauthorized>()("Unauthorized", {
      code: Schema.Literal("unauthorized"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withAuthError),
    [{ code: "unauthorized" }],
  ) {}

/** `429 rateLimited` */
export class RateLimited
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<RateLimited>()("RateLimited", {
      code: Schema.Literal("rateLimited"),
      message: Schema.String,
      details: Details<M.RateLimitedDetails>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withThrottlingError, Category.withRetryable({ throttling: true })),
    [{ code: "rateLimited" }],
  ) {}

/** `500 internal` */
export class Internal
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<Internal>()("Internal", {
      code: Schema.Literal("internal"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withServerError, Category.withRetryable()),
    [{ code: "internal" }],
  ) {}

/** `400 invalidCursor` */
export class InvalidCursor
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<InvalidCursor>()("InvalidCursor", {
      code: Schema.Literal("invalidCursor"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "invalidCursor" }],
  ) {}

/** `404 memberNotFound` */
export class MemberNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<MemberNotFound>()("MemberNotFound", {
      code: Schema.Literal("memberNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "memberNotFound" }],
  ) {}

/** `403 platformNotAvailable` */
export class PlatformNotAvailable
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlatformNotAvailable>()("PlatformNotAvailable", {
      code: Schema.Literal("platformNotAvailable"),
      message: Schema.String,
      details: Details<M.PlatformNotAvailableDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withAuthError),
    [{ code: "platformNotAvailable" }],
  ) {}

/** `404 accountLinkNotFound` */
export class AccountLinkNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<AccountLinkNotFound>()("AccountLinkNotFound", {
      code: Schema.Literal("accountLinkNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "accountLinkNotFound" }],
  ) {}

/** `404 contactNotFound` */
export class ContactNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<ContactNotFound>()("ContactNotFound", {
      code: Schema.Literal("contactNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "contactNotFound" }],
  ) {}

/** `403 workspaceLocked` */
export class WorkspaceLocked
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<WorkspaceLocked>()("WorkspaceLocked", {
      code: Schema.Literal("workspaceLocked"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withAuthError),
    [{ code: "workspaceLocked" }],
  ) {}

/** `404 tagNotFound` */
export class TagNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<TagNotFound>()("TagNotFound", {
      code: Schema.Literal("tagNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "tagNotFound" }],
  ) {}

/** `404 threadNotFound` */
export class ThreadNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<ThreadNotFound>()("ThreadNotFound", {
      code: Schema.Literal("threadNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "threadNotFound" }],
  ) {}

/** `409 accountLinkDisconnected` */
export class AccountLinkDisconnected
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<AccountLinkDisconnected>()("AccountLinkDisconnected", {
      code: Schema.Literal("accountLinkDisconnected"),
      message: Schema.String,
      details: Details<M.AccountLinkDisconnectedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withConflictError),
    [{ code: "accountLinkDisconnected" }],
  ) {}

/** `409 integrationSetupRequired` */
export class IntegrationSetupRequired
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<IntegrationSetupRequired>()("IntegrationSetupRequired", {
      code: Schema.Literal("integrationSetupRequired"),
      message: Schema.String,
      details: Details<M.IntegrationSetupRequiredDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withConflictError),
    [{ code: "integrationSetupRequired" }],
  ) {}

/** `422 capabilityNotSupported` */
export class CapabilityNotSupported
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<CapabilityNotSupported>()("CapabilityNotSupported", {
      code: Schema.Literal("capabilityNotSupported"),
      message: Schema.String,
      details: Details<M.CapabilityNotSupportedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "capabilityNotSupported" }],
  ) {}

/** `429 platformRateLimited` */
export class PlatformRateLimited
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlatformRateLimited>()("PlatformRateLimited", {
      code: Schema.Literal("platformRateLimited"),
      message: Schema.String,
      details: Details<M.PlatformRateLimitedDetails>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withThrottlingError, Category.withRetryable({ throttling: true })),
    [{ code: "platformRateLimited" }],
  ) {}

/** `502 platformError` */
export class PlatformError
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlatformError>()("PlatformError", {
      code: Schema.Literal("platformError"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withServerError, Category.withRetryable()),
    [{ code: "platformError" }],
  ) {}

/** `503 platformUnavailable` */
export class PlatformUnavailable
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlatformUnavailable>()("PlatformUnavailable", {
      code: Schema.Literal("platformUnavailable"),
      message: Schema.String,
      details: Details<M.PlatformUnavailableDetails>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withServerError, Category.withRetryable()),
    [{ code: "platformUnavailable" }],
  ) {}

/** `404 messageNotFound` */
export class MessageNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<MessageNotFound>()("MessageNotFound", {
      code: Schema.Literal("messageNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "messageNotFound" }],
  ) {}

/** `422 threadRestricted` */
export class ThreadRestricted
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<ThreadRestricted>()("ThreadRestricted", {
      code: Schema.Literal("threadRestricted"),
      message: Schema.String,
      details: Details<M.ThreadRestrictedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "threadRestricted" }],
  ) {}

/** `422 mutationWindowClosed` */
export class MutationWindowClosed
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<MutationWindowClosed>()("MutationWindowClosed", {
      code: Schema.Literal("mutationWindowClosed"),
      message: Schema.String,
      details: Details<M.MutationWindowClosedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "mutationWindowClosed" }],
  ) {}

/** `422 messageNotModifiable` */
export class MessageNotModifiable
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<MessageNotModifiable>()("MessageNotModifiable", {
      code: Schema.Literal("messageNotModifiable"),
      message: Schema.String,
      details: Details<M.MessageNotModifiableDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "messageNotModifiable" }],
  ) {}

/** `422 contentRejected` */
export class ContentRejected
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<ContentRejected>()("ContentRejected", {
      code: Schema.Literal("contentRejected"),
      message: Schema.String,
      details: Details<M.ContentRejectedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "contentRejected" }],
  ) {}

/** `403 planRequired` */
export class PlanRequired
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlanRequired>()("PlanRequired", {
      code: Schema.Literal("planRequired"),
      message: Schema.String,
      details: Details<M.PlanRequiredDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withAuthError),
    [{ code: "planRequired" }],
  ) {}

/** `409 sendInProgress` */
export class SendInProgress
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<SendInProgress>()("SendInProgress", {
      code: Schema.Literal("sendInProgress"),
      message: Schema.String,
      details: Details<M.SendInProgressDetails>(),
      requestId: Schema.String,
      retryAfter: Schema.optional(DurationSchema),
    }).pipe(Category.withConflictError, Category.withRetryable()),
    [{ code: "sendInProgress" }],
  ) {}

/** `422 idempotencyKeyReused` */
export class IdempotencyKeyReused
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<IdempotencyKeyReused>()("IdempotencyKeyReused", {
      code: Schema.Literal("idempotencyKeyReused"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "idempotencyKeyReused" }],
  ) {}

/** `422 recipientUnavailable` */
export class RecipientUnavailable
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<RecipientUnavailable>()("RecipientUnavailable", {
      code: Schema.Literal("recipientUnavailable"),
      message: Schema.String,
      details: Details<M.RecipientUnavailableDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "recipientUnavailable" }],
  ) {}

/** `422 platformNotSupported` */
export class PlatformNotSupported
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<PlatformNotSupported>()("PlatformNotSupported", {
      code: Schema.Literal("platformNotSupported"),
      message: Schema.String,
      details: Details<M.PlatformNotSupportedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "platformNotSupported" }],
  ) {}

/** `422 profileAmbiguous` */
export class ProfileAmbiguous
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<ProfileAmbiguous>()("ProfileAmbiguous", {
      code: Schema.Literal("profileAmbiguous"),
      message: Schema.String,
      details: Details<M.ProfileAmbiguousDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "profileAmbiguous" }],
  ) {}

/** `502 sendUnconfirmed` */
export class SendUnconfirmed
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<SendUnconfirmed>()("SendUnconfirmed", {
      code: Schema.Literal("sendUnconfirmed"),
      message: Schema.String,
      details: Details<M.SendUnconfirmedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withServerError),
    [{ code: "sendUnconfirmed" }],
  ) {}

/** `409 nameTaken` */
export class NameTaken
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<NameTaken>()("NameTaken", {
      code: Schema.Literal("nameTaken"),
      message: Schema.String,
      details: Details<M.NameTakenDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withConflictError),
    [{ code: "nameTaken" }],
  ) {}

/** `422 tagLimitReached` */
export class TagLimitReached
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<TagLimitReached>()("TagLimitReached", {
      code: Schema.Literal("tagLimitReached"),
      message: Schema.String,
      details: Details<M.TagLimitReachedDetails>(),
      requestId: Schema.String,
    }).pipe(Category.withBadRequestError),
    [{ code: "tagLimitReached" }],
  ) {}

/** `404 statusNotFound` */
export class StatusNotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ Schema.TaggedError<StatusNotFound>()("StatusNotFound", {
      code: Schema.Literal("statusNotFound"),
      message: Schema.String,
      details: Details<null>(),
      requestId: Schema.String,
    }).pipe(Category.withNotFoundError),
    [{ code: "statusNotFound" }],
  ) {}

/** Errors any operation can fail with. */
export const COMMON_ERRORS = [InvalidRequest, Unauthorized, RateLimited, Internal] as const;

export type CommonError = InstanceType<(typeof COMMON_ERRORS)[number]>;
