// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.EventsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    afterSeq: S.optional(S.Number).pipe(T.Query("afterSeq")),
    type: S.optional(S.Array(Model.EventsListRequestTypeItem)).pipe(T.Query("type")),
    limit: S.optional(S.Number).pipe(T.Query("limit")),
  }).pipe(T.Http({ method: "GET", uri: "/events", code: 200 })),
).annotate({ identifier: "EventsListRequest" }) as any as S.Schema<M.EventsListRequest>;

export type ListError = InboxappOpError;
/**
 * Replay events
 *
 * Reads events in sequence order. A page can hold fewer than `limit` events when some are filtered out; continue from `lastSeq` while `hasMore` is true.
 */
export const list: API.PaginatedOperationMethod<
  M.EventsListRequest,
  M.EventPage,
  ListError,
  InboxappOpContext,
  M.EventPageDataItem
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "events.list",
  input: ListRequest,
  output: Model.EventPage,
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "sequence",
    inputToken: "afterSeq",
    outputToken: "lastSeq",
    items: "data",
    hasNextPage: "hasMore",
    pageSize: "limit",
  },
}));
