// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

/** The messaging platforms available to the team, with what each one supports. */
export * as platforms from "./platforms.ts";
/** The team the API token belongs to, and its members: the Inboxapp users who work in it. */
export * as team from "./team.ts";
/** Platform accounts the team connected to Inboxapp. Every thread belongs to one, and messages are sent from one. */
export * as accountLinks from "./account-links.ts";
/** The team's record of a person, holding its CRM state: status, tags, notes, valuation and default assignee. A contact groups one or more profiles, a person's accounts on the platforms. */
export * as contacts from "./contacts.ts";
/** Conversations between one of the team's account links and one profile. */
export * as threads from "./threads.ts";
/** Messages in a thread, and sending, editing, unsending and reacting to them on the platform. */
export * as messages from "./messages.ts";
/** Labels the team puts on contacts. */
export * as tags from "./tags.ts";
/** The pipeline stages a contact can be in, such as a deal stage. A contact has at most one. */
export * as statuses from "./statuses.ts";
/** The colors of Inboxapp's palette, for tags and statuses. */
export * as colors from "./colors.ts";
/** Changes in the team, as delivered to v2 webhooks. Each event names the object that changed and carries only the values of the change; read the object for its current state. Events are kept for 7 days, up to 25,000 per team. */
export * as events from "./events.ts";
