// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.MessagesListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: Model.Cuid2.pipe(T.Label()),
    order: S.optional(Model.MessagesListRequestOrder).pipe(T.Query("order")),
    expand: S.optional(S.Array(Model.MessagesListRequestExpandItem)).pipe(T.Query("expand")),
    limit: S.optional(S.Number).pipe(T.Query("limit")),
    cursor: S.optional(S.String).pipe(T.Query("cursor")),
  }).pipe(T.Http({ method: "GET", uri: "/threads/{threadId}/messages", code: 200 })),
).annotate({ identifier: "MessagesListRequest" }) as any as S.Schema<M.MessagesListRequest>;

export type ListError =
  | E.InvalidCursor
  | E.PlatformNotAvailable
  | E.ThreadNotFound
  | InboxappOpError;
/** List messages */
export const list: API.PaginatedOperationMethod<
  M.MessagesListRequest,
  M.MessagePage,
  ListError,
  InboxappOpContext,
  M.Message
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "messages.list",
  input: ListRequest,
  output: Model.MessagePage,
  errors: [E.InvalidCursor, E.PlatformNotAvailable, E.ThreadNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
}));

export type GetRequest = M.MessagesGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    expand: S.optional(S.Array(Model.MessagesGetRequestExpandItem)).pipe(T.Query("expand")),
  }).pipe(T.Http({ method: "GET", uri: "/messages/{messageId}", code: 200 })),
).annotate({ identifier: "MessagesGetRequest" }) as any as S.Schema<M.MessagesGetRequest>;

export type GetError = E.PlatformNotAvailable | E.MessageNotFound | InboxappOpError;
/** Get message */
export const get: API.OperationMethod<
  M.MessagesGetRequest,
  M.Message,
  GetError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.get",
  input: GetRequest,
  output: Model.Message,
  errors: [E.PlatformNotAvailable, E.MessageNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type EditRequest = M.MessagesEditRequest;
export const EditRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    content: S.String,
  }).pipe(T.Http({ method: "PATCH", uri: "/messages/{messageId}", code: 200 })),
).annotate({ identifier: "MessagesEditRequest" }) as any as S.Schema<M.MessagesEditRequest>;

export type EditError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.MessageNotFound
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.ThreadRestricted
  | E.MutationWindowClosed
  | E.MessageNotModifiable
  | E.ContentRejected
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/**
 * Edit message
 *
 * Edits the message on the platform. Needs `message:edit`, within the platform's edit window.
 */
export const edit: API.OperationMethod<
  M.MessagesEditRequest,
  M.Message,
  EditError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.edit",
  input: EditRequest,
  output: Model.Message,
  errors: [
    E.PlatformNotAvailable,
    E.WorkspaceLocked,
    E.MessageNotFound,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.ThreadRestricted,
    E.MutationWindowClosed,
    E.MessageNotModifiable,
    E.ContentRejected,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type UnsendRequest = M.MessagesUnsendRequest;
export const UnsendRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    scope: Model.MessagesUnsendRequestScope.pipe(T.Query("scope")),
  }).pipe(T.Http({ method: "DELETE", uri: "/messages/{messageId}", code: 200 })),
).annotate({ identifier: "MessagesUnsendRequest" }) as any as S.Schema<M.MessagesUnsendRequest>;

export type UnsendError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.MessageNotFound
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.ThreadRestricted
  | E.MutationWindowClosed
  | E.MessageNotModifiable
  | E.ContentRejected
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/** Delete message */
export const unsend: API.OperationMethod<
  M.MessagesUnsendRequest,
  M.MessageDeletion,
  UnsendError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.unsend",
  input: UnsendRequest,
  output: Model.MessageDeletion,
  errors: [
    E.PlatformNotAvailable,
    E.WorkspaceLocked,
    E.MessageNotFound,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.ThreadRestricted,
    E.MutationWindowClosed,
    E.MessageNotModifiable,
    E.ContentRejected,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type SendRequest = M.MessagesSendRequest;
export const SendRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idempotencyKey: S.optional(S.String).pipe(T.Header("Idempotency-Key")),
    target: Model.SendRequestTarget,
    content: S.String,
    replyToMessageId: S.optional(Model.Cuid2),
  }).pipe(T.Http({ method: "POST", uri: "/messages", code: 200 })),
).annotate({ identifier: "MessagesSendRequest" }) as any as S.Schema<M.MessagesSendRequest>;

export type SendError =
  | E.PlatformNotAvailable
  | E.PlanRequired
  | E.WorkspaceLocked
  | E.ThreadNotFound
  | E.ContactNotFound
  | E.AccountLinkNotFound
  | E.SendInProgress
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.IdempotencyKeyReused
  | E.ThreadRestricted
  | E.ContentRejected
  | E.RecipientUnavailable
  | E.PlatformNotSupported
  | E.ProfileAmbiguous
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.SendUnconfirmed
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/**
 * Send message
 *
 * `201` for a new send. A replay of an `Idempotency-Key` returns the original result with `200`.
 */
export const send: API.OperationMethod<
  M.MessagesSendRequest,
  M.MessagesSendResponse,
  SendError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.send",
  input: SendRequest,
  output: Model.MessagesSendResponse,
  errors: [
    E.PlatformNotAvailable,
    E.PlanRequired,
    E.WorkspaceLocked,
    E.ThreadNotFound,
    E.ContactNotFound,
    E.AccountLinkNotFound,
    E.SendInProgress,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.IdempotencyKeyReused,
    E.ThreadRestricted,
    E.ContentRejected,
    E.RecipientUnavailable,
    E.PlatformNotSupported,
    E.ProfileAmbiguous,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.SendUnconfirmed,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type HistoryRequest = M.MessagesHistoryRequest;
export const HistoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/messages/{messageId}/history", code: 200 })),
).annotate({ identifier: "MessagesHistoryRequest" }) as any as S.Schema<M.MessagesHistoryRequest>;

export type HistoryError = E.PlatformNotAvailable | E.MessageNotFound | InboxappOpError;
/**
 * Get message history
 *
 * Every version of the message's content, from its edits.
 */
export const history: API.OperationMethod<
  M.MessagesHistoryRequest,
  M.MessageHistory,
  HistoryError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.history",
  input: HistoryRequest,
  output: Model.MessageHistory,
  errors: [E.PlatformNotAvailable, E.MessageNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type ReactRequest = M.MessagesReactRequest;
export const ReactRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    emoji: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/messages/{messageId}/reactions", code: 200 })),
).annotate({ identifier: "MessagesReactRequest" }) as any as S.Schema<M.MessagesReactRequest>;

export type ReactError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.MessageNotFound
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.ThreadRestricted
  | E.MutationWindowClosed
  | E.MessageNotModifiable
  | E.ContentRejected
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/** Add reaction */
export const react: API.OperationMethod<
  M.MessagesReactRequest,
  M.Reactions,
  ReactError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.react",
  input: ReactRequest,
  output: Model.Reactions,
  errors: [
    E.PlatformNotAvailable,
    E.WorkspaceLocked,
    E.MessageNotFound,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.ThreadRestricted,
    E.MutationWindowClosed,
    E.MessageNotModifiable,
    E.ContentRejected,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type UnreactRequest = M.MessagesUnreactRequest;
export const UnreactRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    emoji: S.String.pipe(T.Query("emoji")),
  }).pipe(T.Http({ method: "DELETE", uri: "/messages/{messageId}/reactions", code: 200 })),
).annotate({ identifier: "MessagesUnreactRequest" }) as any as S.Schema<M.MessagesUnreactRequest>;

export type UnreactError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.MessageNotFound
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.ThreadRestricted
  | E.MutationWindowClosed
  | E.MessageNotModifiable
  | E.ContentRejected
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/** Remove reaction */
export const unreact: API.OperationMethod<
  M.MessagesUnreactRequest,
  M.Reactions,
  UnreactError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.unreact",
  input: UnreactRequest,
  output: Model.Reactions,
  errors: [
    E.PlatformNotAvailable,
    E.WorkspaceLocked,
    E.MessageNotFound,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.ThreadRestricted,
    E.MutationWindowClosed,
    E.MessageNotModifiable,
    E.ContentRejected,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type AttachmentRequest = M.MessagesAttachmentRequest;
export const AttachmentRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: Model.Cuid2.pipe(T.Label()),
    index: S.Number.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/messages/{messageId}/attachments/{index}", code: 200 })),
).annotate({
  identifier: "MessagesAttachmentRequest",
}) as any as S.Schema<M.MessagesAttachmentRequest>;

export type AttachmentError = E.PlatformNotAvailable | E.MessageNotFound | InboxappOpError;
/**
 * Get attachment
 *
 * `200` with a fresh URL once ready, `202` while the media is pending or processing. A card index is `invalidRequest`.
 */
export const attachment: API.OperationMethod<
  M.MessagesAttachmentRequest,
  M.AttachmentMedia,
  AttachmentError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "messages.attachment",
  input: AttachmentRequest,
  output: Model.AttachmentMedia,
  errors: [E.PlatformNotAvailable, E.MessageNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
