// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.PlatformsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/platforms", code: 200 })),
).annotate({ identifier: "PlatformsListRequest" }) as any as S.Schema<M.PlatformsListRequest>;

export type ListError = InboxappOpError;
/**
 * List platforms
 *
 * Each platform's capabilities and limits. An account link's `capabilities` can only narrow its platform's.
 */
export const list: API.OperationMethod<
  M.PlatformsListRequest,
  Array<M.PlatformInfo>,
  ListError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "platforms.list",
  input: ListRequest,
  output: S.Array(Model.PlatformInfo),
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
