// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";

export type PlatformInfo = M.PlatformInfo;
export const PlatformInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: Platform,
    name: S.String,
    usernamePrefix: S.String,
    capabilities: S.Array(PlatformInfoCapabilitiesItem),
    limits: PlatformInfoLimits,
    mutationWindows: PlatformInfoMutationWindows,
    threadState: PlatformInfoThreadState,
  }),
).annotate({ identifier: "PlatformInfo" }) as any as S.Schema<M.PlatformInfo>;

export type Platform = M.Platform;
export const Platform = /*@__PURE__*/ S.String as any as S.Schema<M.Platform>;

export type PlatformInfoCapabilitiesItem = M.PlatformInfoCapabilitiesItem;
export const PlatformInfoCapabilitiesItem =
  /*@__PURE__*/ S.String as any as S.Schema<M.PlatformInfoCapabilitiesItem>;

export type PlatformInfoLimits = M.PlatformInfoLimits;
export const PlatformInfoLimits = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    characters: S.NullOr(S.Number),
    mediaCount: S.NullOr(S.Number),
    mediaBytes: S.NullOr(S.Number),
    mediaTypes: S.NullOr(PlatformInfoLimitsMediaTypes),
  }),
).annotate({ identifier: "PlatformInfoLimits" }) as any as S.Schema<M.PlatformInfoLimits>;

export type PlatformInfoLimitsMediaTypes = M.PlatformInfoLimitsMediaTypes;
export const PlatformInfoLimitsMediaTypes = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    image: S.optional(S.Array(S.String)),
    video: S.optional(S.Array(S.String)),
    gif: S.optional(S.Array(S.String)),
    file: S.optional(S.Array(S.String)),
    audio: S.optional(S.Array(S.String)),
  }),
).annotate({
  identifier: "PlatformInfoLimitsMediaTypes",
}) as any as S.Schema<M.PlatformInfoLimitsMediaTypes>;

export type PlatformInfoMutationWindows = M.PlatformInfoMutationWindows;
export const PlatformInfoMutationWindows = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    "message:send": S.optional(S.Number),
    "message:edit": S.optional(S.Number),
    "message:delete:self": S.optional(S.Number),
    "message:unsend": S.optional(S.Number),
    "message:react": S.optional(S.Number),
    "message:reply": S.optional(S.Number),
    "message:forward": S.optional(S.Number),
    "media:image": S.optional(S.Number),
    "media:video": S.optional(S.Number),
    "media:gif": S.optional(S.Number),
    "media:file": S.optional(S.Number),
    "media:audio": S.optional(S.Number),
    "thread:typing:send": S.optional(S.Number),
    "thread:typing:receive": S.optional(S.Number),
    "thread:message-requests": S.optional(S.Number),
    "thread:delete:remote": S.optional(S.Number),
    "directory:typeahead": S.optional(S.Number),
    "thread:archive:observe": S.optional(S.Number),
    "thread:archive:mutate": S.optional(S.Number),
    "thread:read:observe": S.optional(S.Number),
    "thread:read:mutate": S.optional(S.Number),
    "profile:follow": S.optional(S.Number),
    "profile:unfollow": S.optional(S.Number),
  }),
).annotate({
  identifier: "PlatformInfoMutationWindows",
}) as any as S.Schema<M.PlatformInfoMutationWindows>;

export type PlatformInfoThreadState = M.PlatformInfoThreadState;
export const PlatformInfoThreadState = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    archive: S.NullOr(PlatformInfoThreadStateArchive),
    read: S.NullOr(PlatformInfoThreadStateRead),
  }),
).annotate({ identifier: "PlatformInfoThreadState" }) as any as S.Schema<M.PlatformInfoThreadState>;

export type PlatformInfoThreadStateArchive = M.PlatformInfoThreadStateArchive;
export const PlatformInfoThreadStateArchive = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    observe: S.Boolean,
    mutate: S.Boolean,
  }),
).annotate({
  identifier: "PlatformInfoThreadStateArchive",
}) as any as S.Schema<M.PlatformInfoThreadStateArchive>;

export type PlatformInfoThreadStateRead = M.PlatformInfoThreadStateRead;
export const PlatformInfoThreadStateRead = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    observe: S.Boolean,
    mutate: S.Boolean,
  }),
).annotate({
  identifier: "PlatformInfoThreadStateRead",
}) as any as S.Schema<M.PlatformInfoThreadStateRead>;

export type InvalidRequestDetails = M.InvalidRequestDetails;
export const InvalidRequestDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    issues: S.Array(InvalidRequestDetailsIssuesItem),
  }),
).annotate({ identifier: "InvalidRequestDetails" }) as any as S.Schema<M.InvalidRequestDetails>;

export type InvalidRequestDetailsIssuesItem = M.InvalidRequestDetailsIssuesItem;
export const InvalidRequestDetailsIssuesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.Array(InvalidRequestDetailsIssuesItemPathItem),
    message: S.String,
  }),
).annotate({
  identifier: "InvalidRequestDetailsIssuesItem",
}) as any as S.Schema<M.InvalidRequestDetailsIssuesItem>;

export type InvalidRequestDetailsIssuesItemPathItem = M.InvalidRequestDetailsIssuesItemPathItem;
export const InvalidRequestDetailsIssuesItemPathItem = /*@__PURE__*/ S.suspend(() =>
  S.Union([S.String, S.Number]),
).annotate({
  identifier: "InvalidRequestDetailsIssuesItemPathItem",
}) as any as S.Schema<M.InvalidRequestDetailsIssuesItemPathItem>;

export type RateLimitedDetails = M.RateLimitedDetails;
export const RateLimitedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    window: RateLimitedDetailsWindow,
    limit: S.Number,
    resetAt: S.String,
  }),
).annotate({ identifier: "RateLimitedDetails" }) as any as S.Schema<M.RateLimitedDetails>;

export type RateLimitedDetailsWindow = M.RateLimitedDetailsWindow;
export const RateLimitedDetailsWindow =
  /*@__PURE__*/ S.String as any as S.Schema<M.RateLimitedDetailsWindow>;

export type Team = M.Team;
export const Team = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    slug: S.String,
    imageUrl: S.NullOr(S.String),
    currency: S.String,
    allowSupportAccess: S.Boolean,
    createdAt: S.String,
  }),
).annotate({ identifier: "Team" }) as any as S.Schema<M.Team>;

export type MemberPage = M.MemberPage;
export const MemberPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Member),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "MemberPage" }) as any as S.Schema<M.MemberPage>;

export type Member = M.Member;
export const Member = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.NullOr(S.String),
    email: S.String,
    imageUrl: S.NullOr(S.String),
    role: MemberRole,
    createdAt: S.String,
  }),
).annotate({ identifier: "Member" }) as any as S.Schema<M.Member>;

export type MemberRole = M.MemberRole;
export const MemberRole = /*@__PURE__*/ S.String as any as S.Schema<M.MemberRole>;

export type Cuid2 = M.Cuid2;
export const Cuid2 = /*@__PURE__*/ S.String as any as S.Schema<M.Cuid2>;

export type AccountLinksListRequestStatusItem = M.AccountLinksListRequestStatusItem;
export const AccountLinksListRequestStatusItem = /*@__PURE__*/ S.Literals([
  "active",
  "offline",
  "paused",
]) as any as S.Schema<M.AccountLinksListRequestStatusItem>;

export type AccountLinkPage = M.AccountLinkPage;
export const AccountLinkPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(AccountLink),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "AccountLinkPage" }) as any as S.Schema<M.AccountLinkPage>;

export type AccountLink = M.AccountLink;
export const AccountLink = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    platform: Platform,
    platformId: S.String,
    username: S.NullOr(S.String),
    displayName: S.NullOr(S.String),
    avatarUrl: S.NullOr(S.String),
    status: AccountLinkStatus,
    pauseReasons: S.Array(S.String),
    capabilities: S.Array(AccountLinkCapabilitiesItem),
    syncedAt: S.NullOr(S.String),
    createdAt: S.String,
  }),
).annotate({ identifier: "AccountLink" }) as any as S.Schema<M.AccountLink>;

export type AccountLinkStatus = M.AccountLinkStatus;
export const AccountLinkStatus = /*@__PURE__*/ S.String as any as S.Schema<M.AccountLinkStatus>;

export type AccountLinkCapabilitiesItem = M.AccountLinkCapabilitiesItem;
export const AccountLinkCapabilitiesItem =
  /*@__PURE__*/ S.String as any as S.Schema<M.AccountLinkCapabilitiesItem>;

export type PlatformNotAvailableDetails = M.PlatformNotAvailableDetails;
export const PlatformNotAvailableDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: Platform,
  }),
).annotate({
  identifier: "PlatformNotAvailableDetails",
}) as any as S.Schema<M.PlatformNotAvailableDetails>;

export type ContactsListRequestExpandItem = M.ContactsListRequestExpandItem;
export const ContactsListRequestExpandItem = /*@__PURE__*/ S.Literals([
  "status",
  "tags",
  "assignee",
]) as any as S.Schema<M.ContactsListRequestExpandItem>;

export type ContactPage = M.ContactPage;
export const ContactPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Contact),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "ContactPage" }) as any as S.Schema<M.ContactPage>;

export type Contact = M.Contact;
export const Contact = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    profiles: S.Array(Profile),
    statusId: S.NullOr(S.String),
    tagIds: S.Array(S.String),
    notes: S.NullOr(S.String),
    valuation: S.NullOr(S.Number),
    assigneeId: S.NullOr(S.String),
    createdAt: S.String,
    updatedAt: S.String,
    status: S.optional(Status),
    tags: S.optional(S.Array(Tag)),
    assignee: S.optional(Member),
  }),
).annotate({ identifier: "Contact" }) as any as S.Schema<M.Contact>;

export type Profile = M.Profile;
export const Profile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    platform: Platform,
    platformId: S.String,
    username: S.String,
    handle: S.String,
    displayName: S.String,
    avatarUrl: S.NullOr(S.String),
    bio: S.NullOr(S.String),
    location: S.NullOr(S.String),
    websiteUrl: S.NullOr(S.String),
    websiteDomain: S.NullOr(S.String),
    verified: S.Boolean,
    isOrganization: S.Boolean,
    isProtected: S.Boolean,
    followerCount: S.NullOr(S.Number),
    followingCount: S.NullOr(S.Number),
    postCount: S.NullOr(S.Number),
    engagementCount: S.NullOr(S.Number),
    listedCount: S.NullOr(S.Number),
    accountStatus: ProfileAccountStatus,
    platformCreatedAt: S.NullOr(S.String),
    profileUrl: S.NullOr(S.String),
    updatedAt: S.String,
    platformData: ProfilePlatformData,
  }),
).annotate({ identifier: "Profile" }) as any as S.Schema<M.Profile>;

export type ProfileAccountStatus = M.ProfileAccountStatus;
export const ProfileAccountStatus =
  /*@__PURE__*/ S.String as any as S.Schema<M.ProfileAccountStatus>;

export type ProfilePlatformData = M.ProfilePlatformData;
export const ProfilePlatformData = /*@__PURE__*/ S.suspend(() =>
  S.Union([ProfilePlatformDataTwitter, ProfilePlatformDataOther]),
).annotate({ identifier: "ProfilePlatformData" }) as any as S.Schema<M.ProfilePlatformData>;

export type ProfilePlatformDataTwitter = M.ProfilePlatformDataTwitter;
export const ProfilePlatformDataTwitter = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _tag: S.Literal("twitter"),
    badge: S.NullOr(ProfilePlatformDataTwitterBadge),
    profileType: ProfilePlatformDataTwitterProfileType,
    professionalCategory: S.NullOr(S.String),
    urlEntities: S.Array(ProfilePlatformDataTwitterUrlEntitiesItem),
    bannerUrl: S.NullOr(S.String),
    rawData: S.NullOr(S.Record(S.String, S.Unknown)),
  }),
).annotate({
  identifier: "ProfilePlatformDataTwitter",
}) as any as S.Schema<M.ProfilePlatformDataTwitter>;

export type ProfilePlatformDataTwitterBadge = M.ProfilePlatformDataTwitterBadge;
export const ProfilePlatformDataTwitterBadge =
  /*@__PURE__*/ S.String as any as S.Schema<M.ProfilePlatformDataTwitterBadge>;

export type ProfilePlatformDataTwitterProfileType = M.ProfilePlatformDataTwitterProfileType;
export const ProfilePlatformDataTwitterProfileType =
  /*@__PURE__*/ S.String as any as S.Schema<M.ProfilePlatformDataTwitterProfileType>;

export type ProfilePlatformDataTwitterUrlEntitiesItem = M.ProfilePlatformDataTwitterUrlEntitiesItem;
export const ProfilePlatformDataTwitterUrlEntitiesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
    expandedUrl: S.String,
    displayUrl: S.String,
    indices: S.Tuple([S.Number, S.Number]),
  }),
).annotate({
  identifier: "ProfilePlatformDataTwitterUrlEntitiesItem",
}) as any as S.Schema<M.ProfilePlatformDataTwitterUrlEntitiesItem>;

export type ProfilePlatformDataOther = M.ProfilePlatformDataOther;
export const ProfilePlatformDataOther = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _tag: S.String,
  }),
).annotate({
  identifier: "ProfilePlatformDataOther",
}) as any as S.Schema<M.ProfilePlatformDataOther>;

export type Status = M.Status;
export const Status = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    color: S.NullOr(S.String),
    createdAt: S.String,
  }),
).annotate({ identifier: "Status" }) as any as S.Schema<M.Status>;

export type Tag = M.Tag;
export const Tag = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    color: S.String,
  }),
).annotate({ identifier: "Tag" }) as any as S.Schema<M.Tag>;

export type ContactsGetRequestExpandItem = M.ContactsGetRequestExpandItem;
export const ContactsGetRequestExpandItem = /*@__PURE__*/ S.Literals([
  "status",
  "tags",
  "assignee",
]) as any as S.Schema<M.ContactsGetRequestExpandItem>;

export type ThreadsListRequestFolder = M.ThreadsListRequestFolder;
export const ThreadsListRequestFolder = /*@__PURE__*/ S.Literals([
  "inbox",
  "noReply",
  "requests",
  "archived",
  "all",
]) as any as S.Schema<M.ThreadsListRequestFolder>;

export type ThreadsListRequestOrder = M.ThreadsListRequestOrder;
export const ThreadsListRequestOrder = /*@__PURE__*/ S.Literals([
  "desc",
  "asc",
]) as any as S.Schema<M.ThreadsListRequestOrder>;

export type ThreadsListRequestExpandItem = M.ThreadsListRequestExpandItem;
export const ThreadsListRequestExpandItem = /*@__PURE__*/ S.Literals([
  "profile",
  "contact",
  "accountLink",
  "assignee",
]) as any as S.Schema<M.ThreadsListRequestExpandItem>;

export type ThreadPage = M.ThreadPage;
export const ThreadPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Thread),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "ThreadPage" }) as any as S.Schema<M.ThreadPage>;

export type Thread = M.Thread;
export const Thread = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    platform: Platform,
    platformId: S.NullOr(S.String),
    accountLinkId: S.String,
    profileId: S.String,
    contactId: S.String,
    assigneeId: S.NullOr(S.String),
    isRequest: S.Boolean,
    acceptanceState: ThreadAcceptanceState,
    archived: S.Boolean,
    unread: S.Boolean,
    restrictions: S.Array(ThreadRestrictionsItem),
    syncing: S.Boolean,
    typingIndicators: ThreadTypingIndicators,
    lastMessage: S.NullOr(LastMessage),
    activity: S.NullOr(ThreadActivity),
    createdAt: S.String,
    accountLink: S.optional(AccountLink),
    profile: S.optional(Profile),
    contact: S.optional(Contact),
    assignee: S.optional(Member),
  }),
).annotate({ identifier: "Thread" }) as any as S.Schema<M.Thread>;

export type ThreadAcceptanceState = M.ThreadAcceptanceState;
export const ThreadAcceptanceState =
  /*@__PURE__*/ S.String as any as S.Schema<M.ThreadAcceptanceState>;

export type ThreadRestrictionsItem = M.ThreadRestrictionsItem;
export const ThreadRestrictionsItem =
  /*@__PURE__*/ S.String as any as S.Schema<M.ThreadRestrictionsItem>;

export type ThreadTypingIndicators = M.ThreadTypingIndicators;
export const ThreadTypingIndicators =
  /*@__PURE__*/ S.String as any as S.Schema<M.ThreadTypingIndicators>;

export type LastMessage = M.LastMessage;
export const LastMessage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    direction: LastMessageDirection,
    createdAt: S.String,
  }),
).annotate({ identifier: "LastMessage" }) as any as S.Schema<M.LastMessage>;

export type LastMessageDirection = M.LastMessageDirection;
export const LastMessageDirection =
  /*@__PURE__*/ S.String as any as S.Schema<M.LastMessageDirection>;

export type ThreadActivity = M.ThreadActivity;
export const ThreadActivity = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    preview: S.NullOr(S.String),
    direction: ThreadActivityDirection,
    at: S.String,
  }),
).annotate({ identifier: "ThreadActivity" }) as any as S.Schema<M.ThreadActivity>;

export type ThreadActivityDirection = M.ThreadActivityDirection;
export const ThreadActivityDirection =
  /*@__PURE__*/ S.String as any as S.Schema<M.ThreadActivityDirection>;

export type ThreadsGetRequestExpandItem = M.ThreadsGetRequestExpandItem;
export const ThreadsGetRequestExpandItem = /*@__PURE__*/ S.Literals([
  "profile",
  "contact",
  "accountLink",
  "assignee",
]) as any as S.Schema<M.ThreadsGetRequestExpandItem>;

export type ThreadUpdateTypingIndicators = M.ThreadUpdateTypingIndicators;
export const ThreadUpdateTypingIndicators = /*@__PURE__*/ S.Literals([
  "enabled",
  "disabled",
  "teamDefault",
]) as any as S.Schema<M.ThreadUpdateTypingIndicators>;

export type ThreadDeletion = M.ThreadDeletion;
export const ThreadDeletion = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    scope: ThreadDeletionScope,
  }),
).annotate({ identifier: "ThreadDeletion" }) as any as S.Schema<M.ThreadDeletion>;

export type ThreadDeletionScope = M.ThreadDeletionScope;
export const ThreadDeletionScope = /*@__PURE__*/ S.String as any as S.Schema<M.ThreadDeletionScope>;

export type AccountLinkDisconnectedDetails = M.AccountLinkDisconnectedDetails;
export const AccountLinkDisconnectedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountLinkId: S.String,
    status: AccountLinkDisconnectedDetailsStatus,
  }),
).annotate({
  identifier: "AccountLinkDisconnectedDetails",
}) as any as S.Schema<M.AccountLinkDisconnectedDetails>;

export type AccountLinkDisconnectedDetailsStatus = M.AccountLinkDisconnectedDetailsStatus;
export const AccountLinkDisconnectedDetailsStatus =
  /*@__PURE__*/ S.String as any as S.Schema<M.AccountLinkDisconnectedDetailsStatus>;

export type IntegrationSetupRequiredDetails = M.IntegrationSetupRequiredDetails;
export const IntegrationSetupRequiredDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountLinkId: S.String,
  }),
).annotate({
  identifier: "IntegrationSetupRequiredDetails",
}) as any as S.Schema<M.IntegrationSetupRequiredDetails>;

export type CapabilityNotSupportedDetails = M.CapabilityNotSupportedDetails;
export const CapabilityNotSupportedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    capability: CapabilityNotSupportedDetailsCapability,
  }),
).annotate({
  identifier: "CapabilityNotSupportedDetails",
}) as any as S.Schema<M.CapabilityNotSupportedDetails>;

export type CapabilityNotSupportedDetailsCapability = M.CapabilityNotSupportedDetailsCapability;
export const CapabilityNotSupportedDetailsCapability =
  /*@__PURE__*/ S.String as any as S.Schema<M.CapabilityNotSupportedDetailsCapability>;

export type PlatformRateLimitedDetails = M.PlatformRateLimitedDetails;
export const PlatformRateLimitedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    retryAfterSeconds: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "PlatformRateLimitedDetails",
}) as any as S.Schema<M.PlatformRateLimitedDetails>;

export type PlatformUnavailableDetails = M.PlatformUnavailableDetails;
export const PlatformUnavailableDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    retryAfterSeconds: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "PlatformUnavailableDetails",
}) as any as S.Schema<M.PlatformUnavailableDetails>;

export type TypingSignal = M.TypingSignal;
export const TypingSignal = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: TypingSignalStatus,
    reason: S.NullOr(TypingSignalReason),
  }),
).annotate({ identifier: "TypingSignal" }) as any as S.Schema<M.TypingSignal>;

export type TypingSignalStatus = M.TypingSignalStatus;
export const TypingSignalStatus = /*@__PURE__*/ S.String as any as S.Schema<M.TypingSignalStatus>;

export type TypingSignalReason = M.TypingSignalReason;
export const TypingSignalReason = /*@__PURE__*/ S.String as any as S.Schema<M.TypingSignalReason>;

export type MessagesListRequestOrder = M.MessagesListRequestOrder;
export const MessagesListRequestOrder = /*@__PURE__*/ S.Literals([
  "desc",
  "asc",
]) as any as S.Schema<M.MessagesListRequestOrder>;

export type MessagesListRequestExpandItem = M.MessagesListRequestExpandItem;
export const MessagesListRequestExpandItem = /*@__PURE__*/ S.Literals([
  "sentBy",
  "reactions.author",
  "thread",
  "accountLink",
  "replyTo.message",
]) as any as S.Schema<M.MessagesListRequestExpandItem>;

export type MessagePage = M.MessagePage;
export const MessagePage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Message),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "MessagePage" }) as any as S.Schema<M.MessagePage>;

export type Message = M.Message;
export const Message = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    threadId: S.String,
    accountLinkId: S.String,
    platform: Platform,
    platformId: S.NullOr(S.String),
    direction: MessageDirection,
    sentBy: S.NullOr(MessageSentBy),
    content: S.String,
    entities: MessageEntities,
    attachments: S.Array(MessageAttachmentsItem),
    forwarded: S.NullOr(MessageForwarded),
    reactions: S.Array(Reaction),
    editedAt: S.NullOr(S.String),
    deletedAt: S.NullOr(S.String),
    createdAt: S.String,
    platformData: MessagePlatformData,
    replyTo: S.NullOr(MessageReplyTo),
    thread: S.optional(Thread),
    accountLink: S.optional(AccountLink),
  }),
).annotate({ identifier: "Message" }) as any as S.Schema<M.Message>;

export type MessageDirection = M.MessageDirection;
export const MessageDirection = /*@__PURE__*/ S.String as any as S.Schema<M.MessageDirection>;

export type MessageSentBy = M.MessageSentBy;
export const MessageSentBy = /*@__PURE__*/ S.suspend(() =>
  S.Union([MessageSentByMember, MessageSentByAgent, MessageSentByCampaign, MessageSentByApi]),
).annotate({ identifier: "MessageSentBy" }) as any as S.Schema<M.MessageSentBy>;

export type MessageSentByMember = M.MessageSentByMember;
export const MessageSentByMember = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("member"),
    memberId: S.String,
    member: S.optional(Member),
  }),
).annotate({ identifier: "MessageSentByMember" }) as any as S.Schema<M.MessageSentByMember>;

export type MessageSentByAgent = M.MessageSentByAgent;
export const MessageSentByAgent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("agent"),
    agentId: S.String,
    memberId: S.String,
    agent: S.optional(MessageSentByAgentAgent),
    member: S.optional(Member),
  }),
).annotate({ identifier: "MessageSentByAgent" }) as any as S.Schema<M.MessageSentByAgent>;

export type MessageSentByAgentAgent = M.MessageSentByAgentAgent;
export const MessageSentByAgentAgent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
  }),
).annotate({ identifier: "MessageSentByAgentAgent" }) as any as S.Schema<M.MessageSentByAgentAgent>;

export type MessageSentByCampaign = M.MessageSentByCampaign;
export const MessageSentByCampaign = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    campaignId: S.String,
    stepId: S.NullOr(S.String),
  }),
).annotate({ identifier: "MessageSentByCampaign" }) as any as S.Schema<M.MessageSentByCampaign>;

export type MessageSentByApi = M.MessageSentByApi;
export const MessageSentByApi = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("api"),
    tokenId: S.NullOr(S.String),
    token: S.optional(MessageSentByApiToken),
  }),
).annotate({ identifier: "MessageSentByApi" }) as any as S.Schema<M.MessageSentByApi>;

export type MessageSentByApiToken = M.MessageSentByApiToken;
export const MessageSentByApiToken = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
  }),
).annotate({ identifier: "MessageSentByApiToken" }) as any as S.Schema<M.MessageSentByApiToken>;

export type MessageEntities = M.MessageEntities;
export const MessageEntities = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    urls: S.Array(MessageEntitiesUrlsItem),
    postShares: S.Array(MessageEntitiesPostSharesItem),
    mentions: S.Array(MessageEntitiesMentionsItem),
    hashtags: S.Array(MessageEntitiesHashtagsItem),
    cashtags: S.Array(MessageEntitiesCashtagsItem),
    format: S.Array(MessageEntitiesFormatItem),
  }),
).annotate({ identifier: "MessageEntities" }) as any as S.Schema<M.MessageEntities>;

export type MessageEntitiesUrlsItem = M.MessageEntitiesUrlsItem;
export const MessageEntitiesUrlsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
    displayUrl: S.String,
    indices: S.NullOr(MessageEntitiesUrlsItemIndices),
  }),
).annotate({ identifier: "MessageEntitiesUrlsItem" }) as any as S.Schema<M.MessageEntitiesUrlsItem>;

export type MessageEntitiesUrlsItemIndices = M.MessageEntitiesUrlsItemIndices;
export const MessageEntitiesUrlsItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesUrlsItemIndices",
}) as any as S.Schema<M.MessageEntitiesUrlsItemIndices>;

export type MessageEntitiesPostSharesItem = M.MessageEntitiesPostSharesItem;
export const MessageEntitiesPostSharesItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platformId: S.String,
    url: S.String,
    indices: S.NullOr(MessageEntitiesPostSharesItemIndices),
  }),
).annotate({
  identifier: "MessageEntitiesPostSharesItem",
}) as any as S.Schema<M.MessageEntitiesPostSharesItem>;

export type MessageEntitiesPostSharesItemIndices = M.MessageEntitiesPostSharesItemIndices;
export const MessageEntitiesPostSharesItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesPostSharesItemIndices",
}) as any as S.Schema<M.MessageEntitiesPostSharesItemIndices>;

export type MessageEntitiesMentionsItem = M.MessageEntitiesMentionsItem;
export const MessageEntitiesMentionsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    username: S.String,
    displayName: S.NullOr(S.String),
    platformId: S.NullOr(S.String),
    indices: S.NullOr(MessageEntitiesMentionsItemIndices),
  }),
).annotate({
  identifier: "MessageEntitiesMentionsItem",
}) as any as S.Schema<M.MessageEntitiesMentionsItem>;

export type MessageEntitiesMentionsItemIndices = M.MessageEntitiesMentionsItemIndices;
export const MessageEntitiesMentionsItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesMentionsItemIndices",
}) as any as S.Schema<M.MessageEntitiesMentionsItemIndices>;

export type MessageEntitiesHashtagsItem = M.MessageEntitiesHashtagsItem;
export const MessageEntitiesHashtagsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tag: S.String,
    indices: S.NullOr(MessageEntitiesHashtagsItemIndices),
  }),
).annotate({
  identifier: "MessageEntitiesHashtagsItem",
}) as any as S.Schema<M.MessageEntitiesHashtagsItem>;

export type MessageEntitiesHashtagsItemIndices = M.MessageEntitiesHashtagsItemIndices;
export const MessageEntitiesHashtagsItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesHashtagsItemIndices",
}) as any as S.Schema<M.MessageEntitiesHashtagsItemIndices>;

export type MessageEntitiesCashtagsItem = M.MessageEntitiesCashtagsItem;
export const MessageEntitiesCashtagsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    symbol: S.String,
    indices: S.NullOr(MessageEntitiesCashtagsItemIndices),
  }),
).annotate({
  identifier: "MessageEntitiesCashtagsItem",
}) as any as S.Schema<M.MessageEntitiesCashtagsItem>;

export type MessageEntitiesCashtagsItemIndices = M.MessageEntitiesCashtagsItemIndices;
export const MessageEntitiesCashtagsItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesCashtagsItemIndices",
}) as any as S.Schema<M.MessageEntitiesCashtagsItemIndices>;

export type MessageEntitiesFormatItem = M.MessageEntitiesFormatItem;
export const MessageEntitiesFormatItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    kind: MessageEntitiesFormatItemKind,
    indices: MessageEntitiesFormatItemIndices,
  }),
).annotate({
  identifier: "MessageEntitiesFormatItem",
}) as any as S.Schema<M.MessageEntitiesFormatItem>;

export type MessageEntitiesFormatItemKind = M.MessageEntitiesFormatItemKind;
export const MessageEntitiesFormatItemKind =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageEntitiesFormatItemKind>;

export type MessageEntitiesFormatItemIndices = M.MessageEntitiesFormatItemIndices;
export const MessageEntitiesFormatItemIndices = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.Number,
    end: S.Number,
  }),
).annotate({
  identifier: "MessageEntitiesFormatItemIndices",
}) as any as S.Schema<M.MessageEntitiesFormatItemIndices>;

export type MessageAttachmentsItem = M.MessageAttachmentsItem;
export const MessageAttachmentsItem = /*@__PURE__*/ S.suspend(() =>
  S.Union([AttachmentMedia, AttachmentCard]),
).annotate({ identifier: "MessageAttachmentsItem" }) as any as S.Schema<M.MessageAttachmentsItem>;

export type AttachmentMedia = M.AttachmentMedia;
export const AttachmentMedia = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    index: S.Number,
    kind: AttachmentMediaKind,
    filename: S.NullOr(S.String),
    contentType: S.NullOr(S.String),
    sizeBytes: S.NullOr(S.Number),
    width: S.NullOr(S.Number),
    height: S.NullOr(S.Number),
    aspectRatio: S.NullOr(S.Number),
    durationSeconds: S.NullOr(S.Number),
    status: AttachmentMediaStatus,
    url: S.NullOr(S.String),
    expiresAt: S.NullOr(S.String),
    poster: S.NullOr(AttachmentMediaPoster),
  }),
).annotate({ identifier: "AttachmentMedia" }) as any as S.Schema<M.AttachmentMedia>;

export type AttachmentMediaKind = M.AttachmentMediaKind;
export const AttachmentMediaKind = /*@__PURE__*/ S.String as any as S.Schema<M.AttachmentMediaKind>;

export type AttachmentMediaStatus = M.AttachmentMediaStatus;
export const AttachmentMediaStatus =
  /*@__PURE__*/ S.String as any as S.Schema<M.AttachmentMediaStatus>;

export type AttachmentMediaPoster = M.AttachmentMediaPoster;
export const AttachmentMediaPoster = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
    expiresAt: S.NullOr(S.String),
    width: S.NullOr(S.Number),
    height: S.NullOr(S.Number),
  }),
).annotate({ identifier: "AttachmentMediaPoster" }) as any as S.Schema<M.AttachmentMediaPoster>;

export type AttachmentCard = M.AttachmentCard;
export const AttachmentCard = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    index: S.Number,
    kind: S.Literal("card"),
    url: S.String,
    title: S.NullOr(S.String),
    description: S.NullOr(S.String),
    domain: S.NullOr(S.String),
    thumbnail: S.NullOr(AttachmentCardThumbnail),
  }),
).annotate({ identifier: "AttachmentCard" }) as any as S.Schema<M.AttachmentCard>;

export type AttachmentCardThumbnail = M.AttachmentCardThumbnail;
export const AttachmentCardThumbnail = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.String,
    width: S.Number,
    height: S.Number,
    alt: S.NullOr(S.String),
  }),
).annotate({ identifier: "AttachmentCardThumbnail" }) as any as S.Schema<M.AttachmentCardThumbnail>;

export type MessageForwarded = M.MessageForwarded;
export const MessageForwarded = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    content: S.NullOr(S.String),
  }),
).annotate({ identifier: "MessageForwarded" }) as any as S.Schema<M.MessageForwarded>;

export type Reaction = M.Reaction;
export const Reaction = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    emoji: S.String,
    author: ReactionAuthor,
    createdAt: S.NullOr(S.String),
  }),
).annotate({ identifier: "Reaction" }) as any as S.Schema<M.Reaction>;

export type ReactionAuthor = M.ReactionAuthor;
export const ReactionAuthor = /*@__PURE__*/ S.suspend(() =>
  S.Union([ReactionAuthorAccountLink, ReactionAuthorProfile, ReactionAuthorUnknown]),
).annotate({ identifier: "ReactionAuthor" }) as any as S.Schema<M.ReactionAuthor>;

export type ReactionAuthorAccountLink = M.ReactionAuthorAccountLink;
export const ReactionAuthorAccountLink = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("accountLink"),
    accountLinkId: S.String,
    accountLink: S.optional(AccountLink),
  }),
).annotate({
  identifier: "ReactionAuthorAccountLink",
}) as any as S.Schema<M.ReactionAuthorAccountLink>;

export type ReactionAuthorProfile = M.ReactionAuthorProfile;
export const ReactionAuthorProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("profile"),
    profileId: S.String,
    contactId: S.NullOr(S.String),
    profile: S.optional(Profile),
    contact: S.optional(Contact),
  }),
).annotate({ identifier: "ReactionAuthorProfile" }) as any as S.Schema<M.ReactionAuthorProfile>;

export type ReactionAuthorUnknown = M.ReactionAuthorUnknown;
export const ReactionAuthorUnknown = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("unknown"),
    platformId: S.String,
  }),
).annotate({ identifier: "ReactionAuthorUnknown" }) as any as S.Schema<M.ReactionAuthorUnknown>;

export type MessagePlatformData = M.MessagePlatformData;
export const MessagePlatformData = /*@__PURE__*/ S.suspend(() =>
  S.Union([MessagePlatformDataTwitter, MessagePlatformDataOther]),
).annotate({ identifier: "MessagePlatformData" }) as any as S.Schema<M.MessagePlatformData>;

export type MessagePlatformDataTwitter = M.MessagePlatformDataTwitter;
export const MessagePlatformDataTwitter = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _tag: S.Literal("twitter"),
    encrypted: S.Boolean,
  }),
).annotate({
  identifier: "MessagePlatformDataTwitter",
}) as any as S.Schema<M.MessagePlatformDataTwitter>;

export type MessagePlatformDataOther = M.MessagePlatformDataOther;
export const MessagePlatformDataOther = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    _tag: S.String,
  }),
).annotate({
  identifier: "MessagePlatformDataOther",
}) as any as S.Schema<M.MessagePlatformDataOther>;

export type MessageReplyTo = M.MessageReplyTo;
export const MessageReplyTo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: S.NullOr(S.String),
    platformId: S.NullOr(S.String),
    content: S.String,
    authorName: S.NullOr(S.String),
    message: S.optional(Message),
  }),
).annotate({ identifier: "MessageReplyTo" }) as any as S.Schema<M.MessageReplyTo>;

export type MessagesGetRequestExpandItem = M.MessagesGetRequestExpandItem;
export const MessagesGetRequestExpandItem = /*@__PURE__*/ S.Literals([
  "sentBy",
  "reactions.author",
  "thread",
  "accountLink",
  "replyTo.message",
]) as any as S.Schema<M.MessagesGetRequestExpandItem>;

export type ThreadRestrictedDetails = M.ThreadRestrictedDetails;
export const ThreadRestrictedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    capability: ThreadRestrictedDetailsCapability,
  }),
).annotate({ identifier: "ThreadRestrictedDetails" }) as any as S.Schema<M.ThreadRestrictedDetails>;

export type ThreadRestrictedDetailsCapability = M.ThreadRestrictedDetailsCapability;
export const ThreadRestrictedDetailsCapability =
  /*@__PURE__*/ S.String as any as S.Schema<M.ThreadRestrictedDetailsCapability>;

export type MutationWindowClosedDetails = M.MutationWindowClosedDetails;
export const MutationWindowClosedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    capability: MutationWindowClosedDetailsCapability,
    closedAt: S.NullOr(S.String),
  }),
).annotate({
  identifier: "MutationWindowClosedDetails",
}) as any as S.Schema<M.MutationWindowClosedDetails>;

export type MutationWindowClosedDetailsCapability = M.MutationWindowClosedDetailsCapability;
export const MutationWindowClosedDetailsCapability =
  /*@__PURE__*/ S.String as any as S.Schema<M.MutationWindowClosedDetailsCapability>;

export type MessageNotModifiableDetails = M.MessageNotModifiableDetails;
export const MessageNotModifiableDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    reason: S.String,
  }),
).annotate({
  identifier: "MessageNotModifiableDetails",
}) as any as S.Schema<M.MessageNotModifiableDetails>;

export type ContentRejectedDetails = M.ContentRejectedDetails;
export const ContentRejectedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    detail: S.String,
  }),
).annotate({ identifier: "ContentRejectedDetails" }) as any as S.Schema<M.ContentRejectedDetails>;

export type MessagesUnsendRequestScope = M.MessagesUnsendRequestScope;
export const MessagesUnsendRequestScope = /*@__PURE__*/ S.Literals([
  "self",
  "all",
]) as any as S.Schema<M.MessagesUnsendRequestScope>;

export type MessageDeletion = M.MessageDeletion;
export const MessageDeletion = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: S.String,
    scope: MessageDeletionScope,
    deletedAt: S.String,
  }),
).annotate({ identifier: "MessageDeletion" }) as any as S.Schema<M.MessageDeletion>;

export type MessageDeletionScope = M.MessageDeletionScope;
export const MessageDeletionScope =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageDeletionScope>;

export type SendRequestTarget = M.SendRequestTarget;
export const SendRequestTarget = /*@__PURE__*/ S.suspend(() =>
  S.Union([SendRequestTargetThread, SendRequestTargetContact, SendRequestTargetProfile]),
).annotate({ identifier: "SendRequestTarget" }) as any as S.Schema<M.SendRequestTarget>;

export type SendRequestTargetThread = M.SendRequestTargetThread;
export const SendRequestTargetThread = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    threadId: Cuid2,
  }),
).annotate({ identifier: "SendRequestTargetThread" }) as any as S.Schema<M.SendRequestTargetThread>;

export type SendRequestTargetContact = M.SendRequestTargetContact;
export const SendRequestTargetContact = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    accountLinkId: Cuid2,
    contactId: Cuid2,
  }),
).annotate({
  identifier: "SendRequestTargetContact",
}) as any as S.Schema<M.SendRequestTargetContact>;

export type SendRequestTargetProfile = M.SendRequestTargetProfile;
export const SendRequestTargetProfile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("profile"),
    accountLinkId: Cuid2,
    platform: Platform,
    platformId: S.String,
  }),
).annotate({
  identifier: "SendRequestTargetProfile",
}) as any as S.Schema<M.SendRequestTargetProfile>;

export type PlanRequiredDetails = M.PlanRequiredDetails;
export const PlanRequiredDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    feature: S.String,
  }),
).annotate({ identifier: "PlanRequiredDetails" }) as any as S.Schema<M.PlanRequiredDetails>;

export type SendInProgressDetails = M.SendInProgressDetails;
export const SendInProgressDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: S.String,
  }),
).annotate({ identifier: "SendInProgressDetails" }) as any as S.Schema<M.SendInProgressDetails>;

export type RecipientUnavailableDetails = M.RecipientUnavailableDetails;
export const RecipientUnavailableDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    reason: S.String,
  }),
).annotate({
  identifier: "RecipientUnavailableDetails",
}) as any as S.Schema<M.RecipientUnavailableDetails>;

export type PlatformNotSupportedDetails = M.PlatformNotSupportedDetails;
export const PlatformNotSupportedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    platform: Platform,
    supported: S.Array(Platform),
  }),
).annotate({
  identifier: "PlatformNotSupportedDetails",
}) as any as S.Schema<M.PlatformNotSupportedDetails>;

export type ProfileAmbiguousDetails = M.ProfileAmbiguousDetails;
export const ProfileAmbiguousDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contactId: S.String,
    platform: Platform,
  }),
).annotate({ identifier: "ProfileAmbiguousDetails" }) as any as S.Schema<M.ProfileAmbiguousDetails>;

export type SendUnconfirmedDetails = M.SendUnconfirmedDetails;
export const SendUnconfirmedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    messageId: S.String,
  }),
).annotate({ identifier: "SendUnconfirmedDetails" }) as any as S.Schema<M.SendUnconfirmedDetails>;

export type MessageHistory = M.MessageHistory;
export const MessageHistory = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    versions: S.Array(MessageHistoryVersionsItem),
    deletion: S.NullOr(MessageHistoryDeletion),
    times: MessageHistoryTimes,
  }),
).annotate({ identifier: "MessageHistory" }) as any as S.Schema<M.MessageHistory>;

export type MessageHistoryVersionsItem = M.MessageHistoryVersionsItem;
export const MessageHistoryVersionsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    content: S.String,
    createdAt: S.String,
    origin: S.NullOr(MessageHistoryVersionsItemOrigin),
  }),
).annotate({
  identifier: "MessageHistoryVersionsItem",
}) as any as S.Schema<M.MessageHistoryVersionsItem>;

export type MessageHistoryVersionsItemOrigin = M.MessageHistoryVersionsItemOrigin;
export const MessageHistoryVersionsItemOrigin =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageHistoryVersionsItemOrigin>;

export type MessageHistoryDeletion = M.MessageHistoryDeletion;
export const MessageHistoryDeletion = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deletedAt: S.String,
    scope: MessageHistoryDeletionScope,
    origin: S.NullOr(MessageHistoryDeletionOrigin),
  }),
).annotate({ identifier: "MessageHistoryDeletion" }) as any as S.Schema<M.MessageHistoryDeletion>;

export type MessageHistoryDeletionScope = M.MessageHistoryDeletionScope;
export const MessageHistoryDeletionScope =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageHistoryDeletionScope>;

export type MessageHistoryDeletionOrigin = M.MessageHistoryDeletionOrigin;
export const MessageHistoryDeletionOrigin =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageHistoryDeletionOrigin>;

export type MessageHistoryTimes = M.MessageHistoryTimes;
export const MessageHistoryTimes = /*@__PURE__*/ S.String as any as S.Schema<M.MessageHistoryTimes>;

export type Reactions = M.Reactions;
export const Reactions = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    reactions: S.Array(Reaction),
    version: S.Number,
  }),
).annotate({ identifier: "Reactions" }) as any as S.Schema<M.Reactions>;

export type TagPage = M.TagPage;
export const TagPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Tag),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "TagPage" }) as any as S.Schema<M.TagPage>;

export type NameTakenDetails = M.NameTakenDetails;
export const NameTakenDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
  }),
).annotate({ identifier: "NameTakenDetails" }) as any as S.Schema<M.NameTakenDetails>;

export type TagLimitReachedDetails = M.TagLimitReachedDetails;
export const TagLimitReachedDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    max: S.Number,
  }),
).annotate({ identifier: "TagLimitReachedDetails" }) as any as S.Schema<M.TagLimitReachedDetails>;

export type StatusPage = M.StatusPage;
export const StatusPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(Status),
    nextCursor: S.NullOr(S.String),
  }),
).annotate({ identifier: "StatusPage" }) as any as S.Schema<M.StatusPage>;

export type Color = M.Color;
export const Color = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    hex: S.String,
  }),
).annotate({ identifier: "Color" }) as any as S.Schema<M.Color>;

export type EventsListRequestTypeItem = M.EventsListRequestTypeItem;
export const EventsListRequestTypeItem = /*@__PURE__*/ S.Literals([
  "thread.created",
  "thread.deleted",
  "thread.assigned",
  "thread.unassigned",
  "thread.archived",
  "thread.unarchived",
  "thread.typing",
  "message.sent",
  "message.received",
  "message.edited",
  "message.deleted",
  "message.reactionAdded",
  "message.reactionRemoved",
  "contact.statusChanged",
  "contact.tagsChanged",
  "contact.notesChanged",
  "contact.valuationChanged",
  "contact.assigneeChanged",
  "tag.created",
  "tag.updated",
  "tag.deleted",
  "status.created",
  "status.updated",
  "status.deleted",
  "campaign.created",
  "campaign.started",
  "campaign.paused",
  "campaign.resumed",
  "campaign.completed",
  "target.contacted",
  "target.followUpSent",
  "target.replied",
]) as any as S.Schema<M.EventsListRequestTypeItem>;

export type EventPage = M.EventPage;
export const EventPage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.Array(EventPageDataItem),
    lastSeq: S.NullOr(S.Number),
    hasMore: S.Boolean,
  }),
).annotate({ identifier: "EventPage" }) as any as S.Schema<M.EventPage>;

export type EventPageDataItem = M.EventPageDataItem;
export const EventPageDataItem = /*@__PURE__*/ S.suspend(() =>
  S.Union([
    ThreadCreatedEvent,
    ThreadDeletedEvent,
    ThreadAssignedEvent,
    ThreadUnassignedEvent,
    ThreadArchivedEvent,
    ThreadUnarchivedEvent,
    ThreadTypingEvent,
    MessageSentEvent,
    MessageReceivedEvent,
    MessageEditedEvent,
    MessageDeletedEvent,
    MessageReactionAddedEvent,
    MessageReactionRemovedEvent,
    ContactStatusChangedEvent,
    ContactTagsChangedEvent,
    ContactNotesChangedEvent,
    ContactValuationChangedEvent,
    ContactAssigneeChangedEvent,
    TagCreatedEvent,
    TagUpdatedEvent,
    TagDeletedEvent,
    StatusCreatedEvent,
    StatusUpdatedEvent,
    StatusDeletedEvent,
    CampaignCreatedEvent,
    CampaignStartedEvent,
    CampaignPausedEvent,
    CampaignResumedEvent,
    CampaignCompletedEvent,
    TargetContactedEvent,
    TargetFollowUpSentEvent,
    TargetRepliedEvent,
  ]),
).annotate({ identifier: "EventPageDataItem" }) as any as S.Schema<M.EventPageDataItem>;

export type ThreadCreatedEvent = M.ThreadCreatedEvent;
export const ThreadCreatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.created"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadCreatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "ThreadCreatedEvent" }) as any as S.Schema<M.ThreadCreatedEvent>;

export type ThreadCreatedEventObject = M.ThreadCreatedEventObject;
export const ThreadCreatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadCreatedEventObject",
}) as any as S.Schema<M.ThreadCreatedEventObject>;

export type ThreadDeletedEvent = M.ThreadDeletedEvent;
export const ThreadDeletedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.deleted"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadDeletedEventObject,
    data: ThreadDeletedEventData,
  }),
).annotate({ identifier: "ThreadDeletedEvent" }) as any as S.Schema<M.ThreadDeletedEvent>;

export type ThreadDeletedEventObject = M.ThreadDeletedEventObject;
export const ThreadDeletedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadDeletedEventObject",
}) as any as S.Schema<M.ThreadDeletedEventObject>;

export type ThreadDeletedEventData = M.ThreadDeletedEventData;
export const ThreadDeletedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountLinkId: S.String,
    platform: Platform,
  }),
).annotate({ identifier: "ThreadDeletedEventData" }) as any as S.Schema<M.ThreadDeletedEventData>;

export type ThreadAssignedEvent = M.ThreadAssignedEvent;
export const ThreadAssignedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.assigned"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadAssignedEventObject,
    data: ThreadAssignedEventData,
  }),
).annotate({ identifier: "ThreadAssignedEvent" }) as any as S.Schema<M.ThreadAssignedEvent>;

export type ThreadAssignedEventObject = M.ThreadAssignedEventObject;
export const ThreadAssignedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadAssignedEventObject",
}) as any as S.Schema<M.ThreadAssignedEventObject>;

export type ThreadAssignedEventData = M.ThreadAssignedEventData;
export const ThreadAssignedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    assigneeId: S.NullOr(S.String),
  }),
).annotate({ identifier: "ThreadAssignedEventData" }) as any as S.Schema<M.ThreadAssignedEventData>;

export type ThreadUnassignedEvent = M.ThreadUnassignedEvent;
export const ThreadUnassignedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.unassigned"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadUnassignedEventObject,
    data: ThreadUnassignedEventData,
  }),
).annotate({ identifier: "ThreadUnassignedEvent" }) as any as S.Schema<M.ThreadUnassignedEvent>;

export type ThreadUnassignedEventObject = M.ThreadUnassignedEventObject;
export const ThreadUnassignedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadUnassignedEventObject",
}) as any as S.Schema<M.ThreadUnassignedEventObject>;

export type ThreadUnassignedEventData = M.ThreadUnassignedEventData;
export const ThreadUnassignedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    assigneeId: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ThreadUnassignedEventData",
}) as any as S.Schema<M.ThreadUnassignedEventData>;

export type ThreadArchivedEvent = M.ThreadArchivedEvent;
export const ThreadArchivedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.archived"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadArchivedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "ThreadArchivedEvent" }) as any as S.Schema<M.ThreadArchivedEvent>;

export type ThreadArchivedEventObject = M.ThreadArchivedEventObject;
export const ThreadArchivedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadArchivedEventObject",
}) as any as S.Schema<M.ThreadArchivedEventObject>;

export type ThreadUnarchivedEvent = M.ThreadUnarchivedEvent;
export const ThreadUnarchivedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.unarchived"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadUnarchivedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "ThreadUnarchivedEvent" }) as any as S.Schema<M.ThreadUnarchivedEvent>;

export type ThreadUnarchivedEventObject = M.ThreadUnarchivedEventObject;
export const ThreadUnarchivedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ThreadUnarchivedEventObject",
}) as any as S.Schema<M.ThreadUnarchivedEventObject>;

export type ThreadTypingEvent = M.ThreadTypingEvent;
export const ThreadTypingEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("thread.typing"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ThreadTypingEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "ThreadTypingEvent" }) as any as S.Schema<M.ThreadTypingEvent>;

export type ThreadTypingEventObject = M.ThreadTypingEventObject;
export const ThreadTypingEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("thread"),
    id: S.String,
    url: S.String,
  }),
).annotate({ identifier: "ThreadTypingEventObject" }) as any as S.Schema<M.ThreadTypingEventObject>;

export type MessageSentEvent = M.MessageSentEvent;
export const MessageSentEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.sent"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageSentEventObject,
    data: MessageSentEventData,
  }),
).annotate({ identifier: "MessageSentEvent" }) as any as S.Schema<M.MessageSentEvent>;

export type MessageSentEventObject = M.MessageSentEventObject;
export const MessageSentEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({ identifier: "MessageSentEventObject" }) as any as S.Schema<M.MessageSentEventObject>;

export type MessageSentEventData = M.MessageSentEventData;
export const MessageSentEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
  }),
).annotate({ identifier: "MessageSentEventData" }) as any as S.Schema<M.MessageSentEventData>;

export type MessageReceivedEvent = M.MessageReceivedEvent;
export const MessageReceivedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.received"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageReceivedEventObject,
    data: MessageReceivedEventData,
  }),
).annotate({ identifier: "MessageReceivedEvent" }) as any as S.Schema<M.MessageReceivedEvent>;

export type MessageReceivedEventObject = M.MessageReceivedEventObject;
export const MessageReceivedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "MessageReceivedEventObject",
}) as any as S.Schema<M.MessageReceivedEventObject>;

export type MessageReceivedEventData = M.MessageReceivedEventData;
export const MessageReceivedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
  }),
).annotate({
  identifier: "MessageReceivedEventData",
}) as any as S.Schema<M.MessageReceivedEventData>;

export type MessageEditedEvent = M.MessageEditedEvent;
export const MessageEditedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.edited"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageEditedEventObject,
    data: MessageEditedEventData,
  }),
).annotate({ identifier: "MessageEditedEvent" }) as any as S.Schema<M.MessageEditedEvent>;

export type MessageEditedEventObject = M.MessageEditedEventObject;
export const MessageEditedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "MessageEditedEventObject",
}) as any as S.Schema<M.MessageEditedEventObject>;

export type MessageEditedEventData = M.MessageEditedEventData;
export const MessageEditedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
  }),
).annotate({ identifier: "MessageEditedEventData" }) as any as S.Schema<M.MessageEditedEventData>;

export type MessageDeletedEvent = M.MessageDeletedEvent;
export const MessageDeletedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.deleted"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageDeletedEventObject,
    data: MessageDeletedEventData,
  }),
).annotate({ identifier: "MessageDeletedEvent" }) as any as S.Schema<M.MessageDeletedEvent>;

export type MessageDeletedEventObject = M.MessageDeletedEventObject;
export const MessageDeletedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "MessageDeletedEventObject",
}) as any as S.Schema<M.MessageDeletedEventObject>;

export type MessageDeletedEventData = M.MessageDeletedEventData;
export const MessageDeletedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    scope: MessageDeletedEventDataScope,
  }),
).annotate({ identifier: "MessageDeletedEventData" }) as any as S.Schema<M.MessageDeletedEventData>;

export type MessageDeletedEventDataScope = M.MessageDeletedEventDataScope;
export const MessageDeletedEventDataScope =
  /*@__PURE__*/ S.String as any as S.Schema<M.MessageDeletedEventDataScope>;

export type MessageReactionAddedEvent = M.MessageReactionAddedEvent;
export const MessageReactionAddedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.reactionAdded"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageReactionAddedEventObject,
    data: MessageReactionAddedEventData,
  }),
).annotate({
  identifier: "MessageReactionAddedEvent",
}) as any as S.Schema<M.MessageReactionAddedEvent>;

export type MessageReactionAddedEventObject = M.MessageReactionAddedEventObject;
export const MessageReactionAddedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "MessageReactionAddedEventObject",
}) as any as S.Schema<M.MessageReactionAddedEventObject>;

export type MessageReactionAddedEventData = M.MessageReactionAddedEventData;
export const MessageReactionAddedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    emoji: S.String,
    authorPlatformId: S.String,
  }),
).annotate({
  identifier: "MessageReactionAddedEventData",
}) as any as S.Schema<M.MessageReactionAddedEventData>;

export type MessageReactionRemovedEvent = M.MessageReactionRemovedEvent;
export const MessageReactionRemovedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("message.reactionRemoved"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: MessageReactionRemovedEventObject,
    data: MessageReactionRemovedEventData,
  }),
).annotate({
  identifier: "MessageReactionRemovedEvent",
}) as any as S.Schema<M.MessageReactionRemovedEvent>;

export type MessageReactionRemovedEventObject = M.MessageReactionRemovedEventObject;
export const MessageReactionRemovedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("message"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "MessageReactionRemovedEventObject",
}) as any as S.Schema<M.MessageReactionRemovedEventObject>;

export type MessageReactionRemovedEventData = M.MessageReactionRemovedEventData;
export const MessageReactionRemovedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    emoji: S.String,
    authorPlatformId: S.String,
  }),
).annotate({
  identifier: "MessageReactionRemovedEventData",
}) as any as S.Schema<M.MessageReactionRemovedEventData>;

export type ContactStatusChangedEvent = M.ContactStatusChangedEvent;
export const ContactStatusChangedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("contact.statusChanged"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ContactStatusChangedEventObject,
    data: ContactStatusChangedEventData,
  }),
).annotate({
  identifier: "ContactStatusChangedEvent",
}) as any as S.Schema<M.ContactStatusChangedEvent>;

export type ContactStatusChangedEventObject = M.ContactStatusChangedEventObject;
export const ContactStatusChangedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ContactStatusChangedEventObject",
}) as any as S.Schema<M.ContactStatusChangedEventObject>;

export type ContactStatusChangedEventData = M.ContactStatusChangedEventData;
export const ContactStatusChangedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    statusId: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ContactStatusChangedEventData",
}) as any as S.Schema<M.ContactStatusChangedEventData>;

export type ContactTagsChangedEvent = M.ContactTagsChangedEvent;
export const ContactTagsChangedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("contact.tagsChanged"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ContactTagsChangedEventObject,
    data: ContactTagsChangedEventData,
  }),
).annotate({ identifier: "ContactTagsChangedEvent" }) as any as S.Schema<M.ContactTagsChangedEvent>;

export type ContactTagsChangedEventObject = M.ContactTagsChangedEventObject;
export const ContactTagsChangedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ContactTagsChangedEventObject",
}) as any as S.Schema<M.ContactTagsChangedEventObject>;

export type ContactTagsChangedEventData = M.ContactTagsChangedEventData;
export const ContactTagsChangedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tagIds: S.Array(S.String),
  }),
).annotate({
  identifier: "ContactTagsChangedEventData",
}) as any as S.Schema<M.ContactTagsChangedEventData>;

export type ContactNotesChangedEvent = M.ContactNotesChangedEvent;
export const ContactNotesChangedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("contact.notesChanged"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ContactNotesChangedEventObject,
    data: ContactNotesChangedEventData,
  }),
).annotate({
  identifier: "ContactNotesChangedEvent",
}) as any as S.Schema<M.ContactNotesChangedEvent>;

export type ContactNotesChangedEventObject = M.ContactNotesChangedEventObject;
export const ContactNotesChangedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ContactNotesChangedEventObject",
}) as any as S.Schema<M.ContactNotesChangedEventObject>;

export type ContactNotesChangedEventData = M.ContactNotesChangedEventData;
export const ContactNotesChangedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    notes: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ContactNotesChangedEventData",
}) as any as S.Schema<M.ContactNotesChangedEventData>;

export type ContactValuationChangedEvent = M.ContactValuationChangedEvent;
export const ContactValuationChangedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("contact.valuationChanged"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ContactValuationChangedEventObject,
    data: ContactValuationChangedEventData,
  }),
).annotate({
  identifier: "ContactValuationChangedEvent",
}) as any as S.Schema<M.ContactValuationChangedEvent>;

export type ContactValuationChangedEventObject = M.ContactValuationChangedEventObject;
export const ContactValuationChangedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ContactValuationChangedEventObject",
}) as any as S.Schema<M.ContactValuationChangedEventObject>;

export type ContactValuationChangedEventData = M.ContactValuationChangedEventData;
export const ContactValuationChangedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    valuation: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "ContactValuationChangedEventData",
}) as any as S.Schema<M.ContactValuationChangedEventData>;

export type ContactAssigneeChangedEvent = M.ContactAssigneeChangedEvent;
export const ContactAssigneeChangedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("contact.assigneeChanged"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: ContactAssigneeChangedEventObject,
    data: ContactAssigneeChangedEventData,
  }),
).annotate({
  identifier: "ContactAssigneeChangedEvent",
}) as any as S.Schema<M.ContactAssigneeChangedEvent>;

export type ContactAssigneeChangedEventObject = M.ContactAssigneeChangedEventObject;
export const ContactAssigneeChangedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("contact"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "ContactAssigneeChangedEventObject",
}) as any as S.Schema<M.ContactAssigneeChangedEventObject>;

export type ContactAssigneeChangedEventData = M.ContactAssigneeChangedEventData;
export const ContactAssigneeChangedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    assigneeId: S.NullOr(S.String),
  }),
).annotate({
  identifier: "ContactAssigneeChangedEventData",
}) as any as S.Schema<M.ContactAssigneeChangedEventData>;

export type TagCreatedEvent = M.TagCreatedEvent;
export const TagCreatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("tag.created"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TagCreatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "TagCreatedEvent" }) as any as S.Schema<M.TagCreatedEvent>;

export type TagCreatedEventObject = M.TagCreatedEventObject;
export const TagCreatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("tag"),
    id: S.String,
    url: S.String,
  }),
).annotate({ identifier: "TagCreatedEventObject" }) as any as S.Schema<M.TagCreatedEventObject>;

export type TagUpdatedEvent = M.TagUpdatedEvent;
export const TagUpdatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("tag.updated"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TagUpdatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "TagUpdatedEvent" }) as any as S.Schema<M.TagUpdatedEvent>;

export type TagUpdatedEventObject = M.TagUpdatedEventObject;
export const TagUpdatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("tag"),
    id: S.String,
    url: S.String,
  }),
).annotate({ identifier: "TagUpdatedEventObject" }) as any as S.Schema<M.TagUpdatedEventObject>;

export type TagDeletedEvent = M.TagDeletedEvent;
export const TagDeletedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("tag.deleted"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TagDeletedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "TagDeletedEvent" }) as any as S.Schema<M.TagDeletedEvent>;

export type TagDeletedEventObject = M.TagDeletedEventObject;
export const TagDeletedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("tag"),
    id: S.String,
    url: S.String,
  }),
).annotate({ identifier: "TagDeletedEventObject" }) as any as S.Schema<M.TagDeletedEventObject>;

export type StatusCreatedEvent = M.StatusCreatedEvent;
export const StatusCreatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("status.created"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: StatusCreatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "StatusCreatedEvent" }) as any as S.Schema<M.StatusCreatedEvent>;

export type StatusCreatedEventObject = M.StatusCreatedEventObject;
export const StatusCreatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("status"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "StatusCreatedEventObject",
}) as any as S.Schema<M.StatusCreatedEventObject>;

export type StatusUpdatedEvent = M.StatusUpdatedEvent;
export const StatusUpdatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("status.updated"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: StatusUpdatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "StatusUpdatedEvent" }) as any as S.Schema<M.StatusUpdatedEvent>;

export type StatusUpdatedEventObject = M.StatusUpdatedEventObject;
export const StatusUpdatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("status"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "StatusUpdatedEventObject",
}) as any as S.Schema<M.StatusUpdatedEventObject>;

export type StatusDeletedEvent = M.StatusDeletedEvent;
export const StatusDeletedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("status.deleted"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: StatusDeletedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "StatusDeletedEvent" }) as any as S.Schema<M.StatusDeletedEvent>;

export type StatusDeletedEventObject = M.StatusDeletedEventObject;
export const StatusDeletedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("status"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "StatusDeletedEventObject",
}) as any as S.Schema<M.StatusDeletedEventObject>;

export type CampaignCreatedEvent = M.CampaignCreatedEvent;
export const CampaignCreatedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("campaign.created"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: CampaignCreatedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "CampaignCreatedEvent" }) as any as S.Schema<M.CampaignCreatedEvent>;

export type CampaignCreatedEventObject = M.CampaignCreatedEventObject;
export const CampaignCreatedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "CampaignCreatedEventObject",
}) as any as S.Schema<M.CampaignCreatedEventObject>;

export type CampaignStartedEvent = M.CampaignStartedEvent;
export const CampaignStartedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("campaign.started"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: CampaignStartedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "CampaignStartedEvent" }) as any as S.Schema<M.CampaignStartedEvent>;

export type CampaignStartedEventObject = M.CampaignStartedEventObject;
export const CampaignStartedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "CampaignStartedEventObject",
}) as any as S.Schema<M.CampaignStartedEventObject>;

export type CampaignPausedEvent = M.CampaignPausedEvent;
export const CampaignPausedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("campaign.paused"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: CampaignPausedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "CampaignPausedEvent" }) as any as S.Schema<M.CampaignPausedEvent>;

export type CampaignPausedEventObject = M.CampaignPausedEventObject;
export const CampaignPausedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "CampaignPausedEventObject",
}) as any as S.Schema<M.CampaignPausedEventObject>;

export type CampaignResumedEvent = M.CampaignResumedEvent;
export const CampaignResumedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("campaign.resumed"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: CampaignResumedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "CampaignResumedEvent" }) as any as S.Schema<M.CampaignResumedEvent>;

export type CampaignResumedEventObject = M.CampaignResumedEventObject;
export const CampaignResumedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "CampaignResumedEventObject",
}) as any as S.Schema<M.CampaignResumedEventObject>;

export type CampaignCompletedEvent = M.CampaignCompletedEvent;
export const CampaignCompletedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("campaign.completed"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: CampaignCompletedEventObject,
    data: S.Unknown,
  }),
).annotate({ identifier: "CampaignCompletedEvent" }) as any as S.Schema<M.CampaignCompletedEvent>;

export type CampaignCompletedEventObject = M.CampaignCompletedEventObject;
export const CampaignCompletedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "CampaignCompletedEventObject",
}) as any as S.Schema<M.CampaignCompletedEventObject>;

export type TargetContactedEvent = M.TargetContactedEvent;
export const TargetContactedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("target.contacted"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TargetContactedEventObject,
    data: TargetContactedEventData,
  }),
).annotate({ identifier: "TargetContactedEvent" }) as any as S.Schema<M.TargetContactedEvent>;

export type TargetContactedEventObject = M.TargetContactedEventObject;
export const TargetContactedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "TargetContactedEventObject",
}) as any as S.Schema<M.TargetContactedEventObject>;

export type TargetContactedEventData = M.TargetContactedEventData;
export const TargetContactedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    messageId: S.String,
    contactId: S.NullOr(S.String),
    stepNumber: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "TargetContactedEventData",
}) as any as S.Schema<M.TargetContactedEventData>;

export type TargetFollowUpSentEvent = M.TargetFollowUpSentEvent;
export const TargetFollowUpSentEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("target.followUpSent"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TargetFollowUpSentEventObject,
    data: TargetFollowUpSentEventData,
  }),
).annotate({ identifier: "TargetFollowUpSentEvent" }) as any as S.Schema<M.TargetFollowUpSentEvent>;

export type TargetFollowUpSentEventObject = M.TargetFollowUpSentEventObject;
export const TargetFollowUpSentEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "TargetFollowUpSentEventObject",
}) as any as S.Schema<M.TargetFollowUpSentEventObject>;

export type TargetFollowUpSentEventData = M.TargetFollowUpSentEventData;
export const TargetFollowUpSentEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    messageId: S.String,
    contactId: S.NullOr(S.String),
    stepNumber: S.NullOr(S.Number),
  }),
).annotate({
  identifier: "TargetFollowUpSentEventData",
}) as any as S.Schema<M.TargetFollowUpSentEventData>;

export type TargetRepliedEvent = M.TargetRepliedEvent;
export const TargetRepliedEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    seq: S.Number,
    type: S.Literal("target.replied"),
    apiVersion: S.Literal("2"),
    createdAt: S.String,
    object: TargetRepliedEventObject,
    data: TargetRepliedEventData,
  }),
).annotate({ identifier: "TargetRepliedEvent" }) as any as S.Schema<M.TargetRepliedEvent>;

export type TargetRepliedEventObject = M.TargetRepliedEventObject;
export const TargetRepliedEventObject = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.Literal("campaign"),
    id: S.String,
    url: S.String,
  }),
).annotate({
  identifier: "TargetRepliedEventObject",
}) as any as S.Schema<M.TargetRepliedEventObject>;

export type TargetRepliedEventData = M.TargetRepliedEventData;
export const TargetRepliedEventData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: S.String,
    messageId: S.String,
    contactId: S.NullOr(S.String),
    stepNumber: S.NullOr(S.Number),
  }),
).annotate({ identifier: "TargetRepliedEventData" }) as any as S.Schema<M.TargetRepliedEventData>;

export type MessagesSendResponse = M.MessagesSendResponse;
export const MessagesSendResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    message: Message,
    thread: Thread,
    httpStatus: S.Number.pipe(T.ResponseCode()),
  }),
).annotate({ identifier: "MessagesSendResponse" }) as any as S.Schema<M.MessagesSendResponse>;
