// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.StatusesListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/statuses", code: 200 })),
).annotate({ identifier: "StatusesListRequest" }) as any as S.Schema<M.StatusesListRequest>;

export type ListError = InboxappOpError;
/** List statuses */
export const list: API.OperationMethod<
  M.StatusesListRequest,
  M.StatusPage,
  ListError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "statuses.list",
  input: ListRequest,
  output: Model.StatusPage,
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type CreateRequest = M.StatusesCreateRequest;
export const CreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    color: S.optional(S.NullOr(S.String)),
  }).pipe(T.Http({ method: "POST", uri: "/statuses", code: 201 })),
).annotate({ identifier: "StatusesCreateRequest" }) as any as S.Schema<M.StatusesCreateRequest>;

export type CreateError = E.WorkspaceLocked | E.NameTaken | InboxappOpError;
/** Create status */
export const create: API.OperationMethod<
  M.StatusesCreateRequest,
  M.Status,
  CreateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "statuses.create",
  input: CreateRequest,
  output: Model.Status,
  errors: [E.WorkspaceLocked, E.NameTaken],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type GetRequest = M.StatusesGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    statusRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/statuses/{statusRef}", code: 200 })),
).annotate({ identifier: "StatusesGetRequest" }) as any as S.Schema<M.StatusesGetRequest>;

export type GetError = E.StatusNotFound | InboxappOpError;
/** Get status */
export const get: API.OperationMethod<M.StatusesGetRequest, M.Status, GetError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "statuses.get",
    input: GetRequest,
    output: Model.Status,
    errors: [E.StatusNotFound],
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));

export type UpdateRequest = M.StatusesUpdateRequest;
export const UpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    statusRef: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    color: S.optional(S.NullOr(S.String)),
  }).pipe(T.Http({ method: "PATCH", uri: "/statuses/{statusRef}", code: 200 })),
).annotate({ identifier: "StatusesUpdateRequest" }) as any as S.Schema<M.StatusesUpdateRequest>;

export type UpdateError = E.WorkspaceLocked | E.StatusNotFound | E.NameTaken | InboxappOpError;
/** Update status */
export const update: API.OperationMethod<
  M.StatusesUpdateRequest,
  M.Status,
  UpdateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "statuses.update",
  input: UpdateRequest,
  output: Model.Status,
  errors: [E.WorkspaceLocked, E.StatusNotFound, E.NameTaken],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type DeleteRequest = M.StatusesDeleteRequest;
export const DeleteRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    statusRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/statuses/{statusRef}", code: 204 })),
).annotate({ identifier: "StatusesDeleteRequest" }) as any as S.Schema<M.StatusesDeleteRequest>;

export type DeleteError = E.WorkspaceLocked | E.StatusNotFound | InboxappOpError;
/** Delete status */
const delete_: API.OperationMethod<M.StatusesDeleteRequest, void, DeleteError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "statuses.delete",
    input: DeleteRequest,
    errors: [E.WorkspaceLocked, E.StatusNotFound],
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));
export { delete_ as delete };
