// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.TagsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/tags", code: 200 })),
).annotate({ identifier: "TagsListRequest" }) as any as S.Schema<M.TagsListRequest>;

export type ListError = InboxappOpError;
/** List tags */
export const list: API.OperationMethod<M.TagsListRequest, M.TagPage, ListError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "tags.list",
    input: ListRequest,
    output: Model.TagPage,
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));

export type CreateRequest = M.TagsCreateRequest;
export const CreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    color: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/tags", code: 201 })),
).annotate({ identifier: "TagsCreateRequest" }) as any as S.Schema<M.TagsCreateRequest>;

export type CreateError = E.WorkspaceLocked | E.NameTaken | E.TagLimitReached | InboxappOpError;
/** Create tag */
export const create: API.OperationMethod<
  M.TagsCreateRequest,
  M.Tag,
  CreateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "tags.create",
  input: CreateRequest,
  output: Model.Tag,
  errors: [E.WorkspaceLocked, E.NameTaken, E.TagLimitReached],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type GetRequest = M.TagsGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tagRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/tags/{tagRef}", code: 200 })),
).annotate({ identifier: "TagsGetRequest" }) as any as S.Schema<M.TagsGetRequest>;

export type GetError = E.TagNotFound | InboxappOpError;
/** Get tag */
export const get: API.OperationMethod<M.TagsGetRequest, M.Tag, GetError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "tags.get",
    input: GetRequest,
    output: Model.Tag,
    errors: [E.TagNotFound],
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));

export type UpdateRequest = M.TagsUpdateRequest;
export const UpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tagRef: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    color: S.optional(S.String),
  }).pipe(T.Http({ method: "PATCH", uri: "/tags/{tagRef}", code: 200 })),
).annotate({ identifier: "TagsUpdateRequest" }) as any as S.Schema<M.TagsUpdateRequest>;

export type UpdateError = E.WorkspaceLocked | E.TagNotFound | E.NameTaken | InboxappOpError;
/** Update tag */
export const update: API.OperationMethod<
  M.TagsUpdateRequest,
  M.Tag,
  UpdateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "tags.update",
  input: UpdateRequest,
  output: Model.Tag,
  errors: [E.WorkspaceLocked, E.TagNotFound, E.NameTaken],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type DeleteRequest = M.TagsDeleteRequest;
export const DeleteRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tagRef: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/tags/{tagRef}", code: 204 })),
).annotate({ identifier: "TagsDeleteRequest" }) as any as S.Schema<M.TagsDeleteRequest>;

export type DeleteError = E.WorkspaceLocked | E.TagNotFound | InboxappOpError;
/**
 * Delete tag
 *
 * Also removes it from every contact.
 */
const delete_: API.OperationMethod<M.TagsDeleteRequest, void, DeleteError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "tags.delete",
    input: DeleteRequest,
    errors: [E.WorkspaceLocked, E.TagNotFound],
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));
export { delete_ as delete };
