// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type GetRequest = M.TeamGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/team", code: 200 })),
).annotate({ identifier: "TeamGetRequest" }) as any as S.Schema<M.TeamGetRequest>;

export type GetError = InboxappOpError;
/** Get team */
export const get: API.OperationMethod<M.TeamGetRequest, M.Team, GetError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "team.get",
    input: GetRequest,
    output: Model.Team,
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));

export type ListMembersRequest = M.TeamListMembersRequest;
export const ListMembersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    limit: S.optional(S.Number).pipe(T.Query("limit")),
    cursor: S.optional(S.String).pipe(T.Query("cursor")),
  }).pipe(T.Http({ method: "GET", uri: "/members", code: 200 })),
).annotate({ identifier: "TeamListMembersRequest" }) as any as S.Schema<M.TeamListMembersRequest>;

export type ListMembersError = E.InvalidCursor | InboxappOpError;
/** List members */
export const listMembers: API.PaginatedOperationMethod<
  M.TeamListMembersRequest,
  M.MemberPage,
  ListMembersError,
  InboxappOpContext,
  M.Member
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "team.listMembers",
  input: ListMembersRequest,
  output: Model.MemberPage,
  errors: [E.InvalidCursor],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
}));

export type GetMemberRequest = M.TeamGetMemberRequest;
export const GetMemberRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    memberId: Model.Cuid2.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/members/{memberId}", code: 200 })),
).annotate({ identifier: "TeamGetMemberRequest" }) as any as S.Schema<M.TeamGetMemberRequest>;

export type GetMemberError = E.MemberNotFound | InboxappOpError;
/** Get member */
export const getMember: API.OperationMethod<
  M.TeamGetMemberRequest,
  M.Member,
  GetMemberError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "team.getMember",
  input: GetMemberRequest,
  output: Model.Member,
  errors: [E.MemberNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
