// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.

import type * as M from "../../services/types.ts";
import * as API from "../api.ts";
import { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as S from "../schema.ts";
import * as T from "../traits.ts";
import * as E from "./errors.ts";
import * as Model from "./schemas.ts";

export type ListRequest = M.ThreadsListRequest;
export const ListRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accountLinkId: S.optional(S.Array(Model.Cuid2)).pipe(T.Query("accountLinkId")),
    platform: S.optional(S.Array(Model.Platform)).pipe(T.Query("platform")),
    contactId: S.optional(S.Array(Model.Cuid2)).pipe(T.Query("contactId")),
    folder: S.optional(Model.ThreadsListRequestFolder).pipe(T.Query("folder")),
    tag: S.optional(S.Array(S.String)).pipe(T.Query("tag")),
    status: S.optional(S.Array(S.String)).pipe(T.Query("status")),
    assigneeId: S.optional(S.Array(Model.Cuid2)).pipe(T.Query("assigneeId")),
    unassigned: S.optional(S.Boolean).pipe(T.Query("unassigned")),
    campaignId: S.optional(S.Array(Model.Cuid2)).pipe(T.Query("campaignId")),
    q: S.optional(S.String).pipe(T.Query("q")),
    order: S.optional(Model.ThreadsListRequestOrder).pipe(T.Query("order")),
    expand: S.optional(S.Array(Model.ThreadsListRequestExpandItem)).pipe(T.Query("expand")),
    limit: S.optional(S.Number).pipe(T.Query("limit")),
    cursor: S.optional(S.String).pipe(T.Query("cursor")),
  }).pipe(T.Http({ method: "GET", uri: "/threads", code: 200 })),
).annotate({ identifier: "ThreadsListRequest" }) as any as S.Schema<M.ThreadsListRequest>;

export type ListError = E.InvalidCursor | E.PlatformNotAvailable | InboxappOpError;
/**
 * List threads
 *
 * Threads in inbox order, filtered by folder and by contact CRM state.
 */
export const list: API.PaginatedOperationMethod<
  M.ThreadsListRequest,
  M.ThreadPage,
  ListError,
  InboxappOpContext,
  M.Thread
> = /*@__PURE__*/ API.makePaginated(() => ({
  id: "threads.list",
  input: ListRequest,
  output: Model.ThreadPage,
  errors: [E.InvalidCursor, E.PlatformNotAvailable],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "cursor",
    inputToken: "cursor",
    outputToken: "nextCursor",
    items: "data",
    pageSize: "limit",
  },
}));

export type GetRequest = M.ThreadsGetRequest;
export const GetRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: Model.Cuid2.pipe(T.Label()),
    expand: S.optional(S.Array(Model.ThreadsGetRequestExpandItem)).pipe(T.Query("expand")),
  }).pipe(T.Http({ method: "GET", uri: "/threads/{threadId}", code: 200 })),
).annotate({ identifier: "ThreadsGetRequest" }) as any as S.Schema<M.ThreadsGetRequest>;

export type GetError = E.PlatformNotAvailable | E.ThreadNotFound | InboxappOpError;
/** Get thread */
export const get: API.OperationMethod<M.ThreadsGetRequest, M.Thread, GetError, InboxappOpContext> =
  /*@__PURE__*/ API.make(() => ({
    id: "threads.get",
    input: GetRequest,
    output: Model.Thread,
    errors: [E.PlatformNotAvailable, E.ThreadNotFound],
    protocol: InboxappProtocol,
    retry: Retry.Retry,
  }));

export type UpdateRequest = M.ThreadsUpdateRequest;
export const UpdateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: Model.Cuid2.pipe(T.Label()),
    archived: S.optional(S.Boolean),
    unread: S.optional(S.Boolean),
    assigneeId: S.optional(S.NullOr(Model.Cuid2)),
    typingIndicators: S.optional(Model.ThreadUpdateTypingIndicators),
  }).pipe(T.Http({ method: "PATCH", uri: "/threads/{threadId}", code: 200 })),
).annotate({ identifier: "ThreadsUpdateRequest" }) as any as S.Schema<M.ThreadsUpdateRequest>;

export type UpdateError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ThreadNotFound
  | InboxappOpError;
/** Update thread */
export const update: API.OperationMethod<
  M.ThreadsUpdateRequest,
  M.Thread,
  UpdateError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "threads.update",
  input: UpdateRequest,
  output: Model.Thread,
  errors: [E.PlatformNotAvailable, E.WorkspaceLocked, E.ThreadNotFound],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));

export type DeleteRequest = M.ThreadsDeleteRequest;
export const DeleteRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: Model.Cuid2.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/threads/{threadId}", code: 200 })),
).annotate({ identifier: "ThreadsDeleteRequest" }) as any as S.Schema<M.ThreadsDeleteRequest>;

export type DeleteError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ThreadNotFound
  | E.AccountLinkDisconnected
  | E.IntegrationSetupRequired
  | E.CapabilityNotSupported
  | E.PlatformRateLimited
  | E.PlatformError
  | E.PlatformUnavailable
  | InboxappOpError;
/**
 * Delete thread
 *
 * Deletes the conversation on the platform when it can, and always in Inboxapp. The response's `scope` says which happened.
 */
const delete_: API.OperationMethod<
  M.ThreadsDeleteRequest,
  M.ThreadDeletion,
  DeleteError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "threads.delete",
  input: DeleteRequest,
  output: Model.ThreadDeletion,
  errors: [
    E.PlatformNotAvailable,
    E.WorkspaceLocked,
    E.ThreadNotFound,
    E.AccountLinkDisconnected,
    E.IntegrationSetupRequired,
    E.CapabilityNotSupported,
    E.PlatformRateLimited,
    E.PlatformError,
    E.PlatformUnavailable,
  ],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
export { delete_ as delete };

export type TypingRequest = M.ThreadsTypingRequest;
export const TypingRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    threadId: Model.Cuid2.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/threads/{threadId}/typing", code: 202 })),
).annotate({ identifier: "ThreadsTypingRequest" }) as any as S.Schema<M.ThreadsTypingRequest>;

export type TypingError =
  | E.PlatformNotAvailable
  | E.WorkspaceLocked
  | E.ThreadNotFound
  | E.CapabilityNotSupported
  | InboxappOpError;
/**
 * Send typing indicator
 *
 * Shows the account link as typing in the conversation. At most one per thread every 2.5 seconds; extra calls return `skipped`.
 */
export const typing: API.OperationMethod<
  M.ThreadsTypingRequest,
  M.TypingSignal,
  TypingError,
  InboxappOpContext
> = /*@__PURE__*/ API.make(() => ({
  id: "threads.typing",
  input: TypingRequest,
  output: Model.TypingSignal,
  errors: [E.PlatformNotAvailable, E.WorkspaceLocked, E.ThreadNotFound, E.CapabilityNotSupported],
  protocol: InboxappProtocol,
  retry: Retry.Retry,
}));
