/**
 * The Effect client for the Inboxapp API v2.
 *
 * ```ts
 * import * as Inboxapp from "@inboxapp/sdk/effect";
 *
 * const page = yield* Inboxapp.threads.list({ folder: "inbox" });
 * ```
 *
 * `./services` is generated by `scripts/generate.ts`; everything else in this folder is hand-written.
 */
export * as Category from "./category.ts";
export { Credentials, CredentialsFromEnv, fromToken, type Settings } from "./credentials.ts";
export { InboxappParseError, UnknownInboxappError } from "./errors.ts";
export { InboxappProtocol, type InboxappOpContext, type InboxappOpError } from "./protocol.ts";
export * as Retry from "./retry.ts";
export * as T from "./traits.ts";
export * as ResponseValidation from "./validation.ts";
export type { OperationMethod, PaginatedOperationMethod } from "./api.ts";
export * from "./services/errors.ts";
export * as Schemas from "./services/schemas.ts";
export * as Webhooks from "./services/webhooks.ts";
export * from "./services/index.ts";
