import { Prelude, shapeName, Trait, type Member, type Model, type Shape } from "./model.ts";
import { documentationOf, enumValues, isNamed, isNullable, isRequired } from "./sdk.ts";

export const BANNER =
  "// AUTO-GENERATED by scripts/generate.ts from .generated-specs/inboxapp.json. Do not edit.\n";

const PRELUDE_TYPES: Record<string, string> = {
  [Prelude.String]: "string",
  [Prelude.Integer]: "number",
  [Prelude.Double]: "number",
  [Prelude.Boolean]: "boolean",
  [Prelude.Document]: "unknown",
  [Prelude.Unit]: "null",
};

export function doc(text: string | undefined, indent = ""): string {
  if (!text) return "";
  const lines = text.replace(/\*\//g, "*\\/").split("\n");
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((line) => `${indent} * ${line}`.trimEnd()).join("\n")}\n${indent} */\n`;
}

export const propertyKey = (name: string) =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);

/** The TypeScript type of a shape reference. `qualify` prefixes names with a namespace import. */
export function typeOf(model: Model, target: string, qualify = (name: string) => name): string {
  const prelude = PRELUDE_TYPES[target];
  if (prelude) return prelude;
  const shape = model.shapes[target];
  if (!shape) throw new Error(`Dangling shape target: ${target}`);
  if (isNamed(shape)) return qualify(shapeName(target));

  switch (shape.type) {
    case "enum":
      return JSON.stringify(enumValues(shape)[0]);
    case "list": {
      const item = withNull(typeOf(model, shape.member.target, qualify), shape.member);
      const length = shape.traits?.[Trait.tuple] as number | undefined;
      return length ? `[${Array(length).fill(item).join(", ")}]` : `Array<${item}>`;
    }
    case "map":
      return `Record<string, ${withNull(typeOf(model, shape.value.target, qualify), shape.value)}>`;
    default:
      return JSON.stringify(shape.traits?.[Trait.constant]);
  }
}

const withNull = (type: string, member: Member) => (isNullable(member) ? `${type} | null` : type);

export function memberType(model: Model, member: Member, qualify?: (name: string) => string) {
  return withNull(typeOf(model, member.target, qualify), member);
}

export function declaration(model: Model, id: string, shape: Shape): string | undefined {
  if (!isNamed(shape)) return undefined;
  const name = shapeName(id);
  const comment = doc(documentationOf(shape));

  switch (shape.type) {
    case "structure": {
      const members = Object.entries(shape.members).map(
        ([key, member]) =>
          doc(documentationOf(member), "  ") +
          `  ${propertyKey(key)}${isRequired(member) ? "" : "?"}: ${memberType(model, member)};`,
      );
      if (shape.traits?.[Trait.open]) members.push("  [key: string]: unknown;");
      return `${comment}export interface ${name} {\n${members.join("\n")}\n}\n`;
    }
    case "union": {
      const variants = Object.values(shape.members).map((member) => typeOf(model, member.target));
      return `${comment}export type ${name} = ${variants.join(" | ")};\n`;
    }
    case "enum": {
      const values = enumValues(shape).map((value) => JSON.stringify(value));
      if (shape.traits?.[Trait.open]) values.push("(string & {})");
      return `${comment}export type ${name} = ${values.join(" | ")};\n`;
    }
    default:
      return `${comment}export type ${name} = ${PRELUDE_TYPES[`smithy.api#${shape.type[0]!.toUpperCase()}${shape.type.slice(1)}`]};\n`;
  }
}
